vuejs-translations/docs-ja

src/guide/essentials/application.md

resolves #116
Cherry picked from https://github.com/vuejs/docs/commit/7f277167551347d16365809f7c9834a3c970215d

docs: fix typo (#116)

---

src/sponsor/index.md

resolves #120
Cherry picked from https://github.com/vuejs/docs/commit/a3247067c6f0cb79d2e70208c20f7ac3e2a11c83

minor sponsor page order tweak (#120)

---

.vitepress/theme/components/VueJobs.vue
.vitepress/theme/index.ts
src/sponsor/index.md

resolves #122
Cherry picked from https://github.com/vuejs/docs/commit/16b772ddeeee6d5be0fc2dcbee40704761f83dec

Add vue.js jobs widget (#122)

---

.vitepress/theme/components/Banner.vue

resolves #124
Cherry picked from https://github.com/vuejs/docs/commit/568bb2d9d255cfebf81b0c5fe996bb9401330288

update banner (#124)

---

.vitepress/theme/components/PreferenceSwitch.vue

resolves #126
Cherry picked from https://github.com/vuejs/docs/commit/37714eea9036fb21e1451e1d30746a3caeaba80a

fix: API preferences link is getting squished (#126)

---

src/public/service-worker.js

resolves #128
Cherry picked from https://github.com/vuejs/docs/commit/ed342ca3cc052013eae7afbf21766d33c797b707

add service worker for clearing v2 cache (#128)

---

src/guide/best-practices/performance.md
src/guide/built-ins/suspense.md
src/guide/scaling-up/routing.md
src/guide/scaling-up/testing.md

resolves #130
Cherry picked from https://github.com/vuejs/docs/commit/5afee150466ed940a84f8a6295c037fc0de750fa

remove next references (#130)

---

.vitepress/theme/components/Home.vue

resolves #132
Cherry picked from https://github.com/vuejs/docs/commit/414dbbe28600801490bd060df9d145687eea40d3

fix: special sponsors link on homepage is broken (#132)

---

package.json

resolves #115 
vuejs/docs@1f2f45b の取り込みです

add preinstall hook to allow only pnpm

---

src/guide/built-ins/transition.md
src/guide/essentials/reactivity-fundamentals.md
src/tutorial/src/step-10/description.md

resolves #140
Cherry picked from https://github.com/vuejs/docs/commit/6d9fc6abc70ed84776557e7b44551913feb8d241

Fix typo (#140)

---

.vitepress/config.ts

resolves #157
Cherry picked from https://github.com/vuejs/docs/commit/798049799cbe54866a78915966a7e403cba6ae9f

add analytics (#157)

---

src/guide/quick-start.md
src/guide/scaling-up/testing.md

resolves #162
Cherry picked from https://github.com/vuejs/docs/commit/7b3a5a3f4cfcd7fac1b474a77da63b4d642592d0

docs: small typo (#162)

---

.vitepress/config.ts

resolves #167
Cherry picked from https://github.com/vuejs/docs/commit/8573bd5b3fc93913d7bb5b45e393f30d7abbe225

fix minify flag (#167)

---

src/public/_redirects

resolves #169
Cherry picked from https://github.com/vuejs/docs/commit/868aeebc4470bc4fea900cd771e934fcbae1b0d7

improve redirects (#169)

---

src/guide/scaling-up/ssr.md

resolves #171
Cherry picked from https://github.com/vuejs/docs/commit/393cd2765edb8d0a1a6ab2c0daf3d0968e2e5403

fork in stackblitz URL (#171)

---

src/public/_redirects

revert redirect

---

src/public/_redirects

test redirect fix

---

src/public/_redirects

add redirect params and use 302 for v2 redirects

---

src/api/application.md

resolves #176
Cherry picked from https://github.com/vuejs/docs/commit/062b1a9c24aaf39902c80a18542eff71045ac209

Update application.md (#176)

---

src/public/_redirects

resolves #183
Cherry picked from https://github.com/vuejs/docs/commit/c17fa6480b61739ec710b52b055dfcc6f6c87951

add missing redirect (#183)

---

src/about/team/members-core.json
src/guide/typescript/options-api.md

resolves #187
Cherry picked from https://github.com/vuejs/docs/commit/291c8e46009d9d6f056c278a3ec4425c813de2e5

docs(team): add pikax (#187)

---

src/tutorial/src/step-2/description.md

resolves #189
Cherry picked from https://github.com/vuejs/docs/commit/1bbc9505c700257f3a92fd48f39801c6301981cb

Use counter variable, not undefined state (#189)

---

README.md

Remove WIP notice

---

src/api/utility-types.md
src/guide/extras/demos/SpreadSheet.vue

resolves #197
Cherry picked from https://github.com/vuejs/docs/commit/02f8947057e2b6e69b93981a9f63f7a4d5524f08

Remove scrollbars from the spreadsheet cells (#197)

---

src/api/utility-types.md
src/guide/essentials/application.md
src/guide/essentials/component-basics.md
src/guide/essentials/forms.md
src/guide/essentials/lifecycle.md
src/guide/essentials/list.md
src/guide/essentials/reactivity-fundamentals.md
src/guide/essentials/template-syntax.md
src/guide/extras/demos/SpreadSheet.vue

resolves #199
Cherry picked from https://github.com/vuejs/docs/commit/6a587d9cce5a107b7f567ae65da26bd4773eb973

Minor tweaks to the guides in Essentials (#199)

---

src/tutorial/src/step-5/description.md

resolves #201
Cherry picked from https://github.com/vuejs/docs/commit/542c35d93b65149b4affdbc0104436a80c27f81f

Typo in link to the forms guide (#201)

---

src/api/options-state.md
src/tutorial/src/step-5/description.md

resolves #203
Cherry picked from https://github.com/vuejs/docs/commit/cbe5afa878a88ac99f68fab9c7e476ddba7abd78

Typo (#203)

---

src/guide/scaling-up/ssr.md

resolves #209
Cherry picked from https://github.com/vuejs/docs/commit/d3cf6cdac22a82e30f593a5e652234345faa051d

chore: fix typos (#209)

---

src/api/options-composition.md

resolves #213
Cherry picked from https://github.com/vuejs/docs/commit/63c23baf91391b539a7322eb2a87eba00e1426fb

fixed a typo (#213)

---

src/guide/scaling-up/testing.md

resolves #216
Cherry picked from https://github.com/vuejs/docs/commit/6ae8590d8355e540f376d2d25bb0eb7bf8ea49d9

minor testing tweaks (#216)

---

.vitepress/theme/components/VueJobs.vue

resolves #218
Cherry picked from https://github.com/vuejs/docs/commit/a20861c4730ee4cfc62b2af6d770f18270bd2f01

tweak posting to show avatar (#218)

---

.vitepress/config.ts

resolves #220
Cherry picked from https://github.com/vuejs/docs/commit/d068a4ce69a51499b9463563c69cdce236d303a2

build: improve chunk stability across builds (#220)

---

.vitepress/config.ts
package.json
pnpm-lock.yaml

resolve #222 
https://github.com/vuejs/docs/commit/b1854805e3c61fe4c493486df5203dc72c5004b9

bump vitepress + remove no longer necessary chunks config

---

src/guide/components/slots.md

resolves #225
Cherry picked from https://github.com/vuejs/docs/commit/9c4eebf9136001572b0696cac0447b9fdad47142

Add missing slash in closing header tag (#225)

---

src/guide/scaling-up/sfc.md

resolves #229
Cherry picked from https://github.com/vuejs/docs/commit/98a0eef55889d4c362f15d56a9eda549c7d04fd6

fix : typo (#229)

---

src/about/team/Member.ts
src/about/team/members-core.json

resolves #233
Cherry picked from https://github.com/vuejs/docs/commit/38d8292e74ea27d22dc58056a0a4cb171b664075

chore: fixing type errors with core members json (#233)

---

src/api/built-in-special-attributes.md
src/api/sfc-spec.md
src/ecosystem/themes/themes.json
src/guide/essentials/forms.md
src/guide/extras/web-components.md
src/guide/scaling-up/sfc.md
src/guide/scaling-up/tooling.md
src/guide/typescript/overview.md
src/style-guide/rules-use-with-caution.md

resolves #239
Cherry picked from https://github.com/vuejs/docs/commit/4429b73a16dfa80b3a970e2bba0e17b4aefd3555

Migrate changes from master to main (#239)

---

src/api/built-in-special-attributes.md
src/api/sfc-spec.md
src/ecosystem/themes/themes.json
src/guide/components/registration.md
src/guide/essentials/forms.md
src/guide/extras/web-components.md
src/guide/scaling-up/sfc.md
src/guide/scaling-up/tooling.md
src/guide/typescript/overview.md
src/style-guide/rules-use-with-caution.md

resolves #241
Cherry picked from https://github.com/vuejs/docs/commit/1fe88c4535cbbf64ca1c86c5d1524820ca373532

Update registration.md (#241)

---

src/api/composition-api-lifecycle.md

resolves #248
Cherry picked from https://github.com/vuejs/docs/commit/aebb35285427e8f4668c5ed6251652f1b8a2f953

Fix unUnmounted to onUnmounted (#248)

---

src/tutorial/src/step-1/description.md

resolves #250
Cherry picked from https://github.com/vuejs/docs/commit/90f3521471befc1526623a34aa746b505d46da19

fixed typo on pg1 of tutorial (#250)

---

src/examples/src/cells/App/template.html

resolves #258
Cherry picked from https://github.com/vuejs/docs/commit/2ffa0d022852dedc911169635c6b1327ea706e00

fix: fix the `v-for` attribute value (#258)

---

src/api/sfc-script-setup.md

resolves #260
Cherry picked from https://github.com/vuejs/docs/commit/e313478645aaa91b65ad612e936bd3f1c3c20e5b

Add a section about custom directives with script setup (#260)

---

.vitepress/config.ts

resolves #265
Cherry picked from https://github.com/vuejs/docs/commit/34b0e9819871399c95ccba909099395ab18eeaf1

use spa mode for analytics script (#265)

---

.vitepress/config.ts

resolves #267
Cherry picked from https://github.com/vuejs/docs/commit/eff9148eb6863493ad5646d195a55d6245afbf79

chore: config refactor [ci skip] (#267)

---

.vitepress/theme/components/PreferenceSwitch.vue

resolves #279
Cherry picked from https://github.com/vuejs/docs/commit/f27b2bcbc8034b2e9cc4676253fc79b0a29fa0ea

persist perference switch open state (#279)

---

.vitepress/theme/components/PreferenceSwitch.vue

resolve #281 
https://github.com/vuejs/docs/commit/bfdad7609f91b945adb97c1896df91bdd4fcef51 の適用

always keep preference switch open

---

.vitepress/theme/components/VueSchoolLink.vue
.vitepress/theme/index.ts
src/guide/components/events.md
src/guide/components/props.md
src/guide/components/slots.md
src/guide/essentials/class-and-style.md
src/guide/essentials/computed.md
src/guide/essentials/conditional.md
src/guide/essentials/event-handling.md
src/guide/essentials/forms.md
src/guide/essentials/list.md
src/guide/essentials/reactivity-fundamentals.md
src/guide/scaling-up/routing.md

resolves #282
Cherry picked from https://github.com/vuejs/docs/commit/05c75f60a33e5092a0eba44c81bccab7fef0fe82

add Vue School links (#282)

---

src/api/sfc-script-setup.md

sfc-script-setup.md 追加箇所の翻訳

---

src/style-guide/rules-strongly-recommended.md

resolves #290
Cherry picked from https://github.com/vuejs/docs/commit/4fe51f8e065771df2c5704866ee698b0839cd64a

Change Vuex to Pinia and link it (#290)

---

src/api/application.md

resolves #295
Cherry picked from https://github.com/vuejs/docs/commit/8ab89bee570432c875eeec4ac01f43ef36a52b3c

chore: update performance mark api ref (#295)

---

src/guide/built-ins/teleport.md
src/guide/components/registration.md
src/guide/essentials/event-handling.md
src/guide/scaling-up/tooling.md

resolves #306
Cherry picked from https://github.com/vuejs/docs/commit/3acc78f513935daa2de6224a1a9025ec30266ca7

4 more Vue School Video Links (CAPI events, teleport, component registration, devtools) (#306)

---

src/guide/built-ins/teleport.md
src/guide/components/registration.md
src/guide/essentials/event-handling.md
src/guide/scaling-up/tooling.md

resolves #308
Cherry picked from https://github.com/vuejs/docs/commit/78b7bce19e315f38b8a73cbefffe4f4600cdaaba

Fix mismatched quotes in import (#308)

---

.vitepress/theme/styles/inline-demo.css
src/guide/built-ins/teleport.md
src/guide/components/registration.md
src/guide/essentials/event-handling.md
src/guide/scaling-up/tooling.md

resolves #310
Cherry picked from https://github.com/vuejs/docs/commit/0566ff1e24a1843038c2df3db5bf76b8e8b4fda4

Dark-mode styling for select and option elements (#310)

---

src/guide/essentials/conditional.md

resolve #12 
おおむね、以前のものを踏襲して翻訳しました。
https://v3.ja.vuejs.org/guide/conditional.html

docs: Guide > Essentials > Conditional Rendering

---

.vitepress/config.ts
.vitepress/theme/components/VueSchoolLink.vue
src/guide/essentials/computed.md

resolve #10 
ご確認のほどよろしくお願い致します！

「Guide > Essentials > Computed Properties」の翻訳

---

src/guide/extras/web-components.md

「Guide > Extra Topics > Vue and Web Components」の翻訳

---

src/guide/essentials/component-basics.md

resolves #335
Cherry picked from https://github.com/vuejs/docs/commit/ce74774edcb512635038661085cb18509b8a206a

Update component-basics.md (#335)

---

src/tutorial/src/step-6/description.md

「Tutorial > Conditional Rendering」の翻訳

---

src/api/composition-api-setup.md

resolve #61
レビューよろしくお願いいたします🙇‍♂️
一部の文言は旧Vue3系のドキュメントを参考にしました
https://v3.ja.vuejs.org/guide/composition-api-setup.html#%E5%BC%95%E6%95%B0

「API > Composition API > Composition API: setup()」の翻訳

---

src/api/built-in-special-elements.md

resolves #349
Cherry picked from https://github.com/vuejs/docs/commit/c0a225f313b0ec7b65d7393730059bb51e26d022

, expected (#349)

---

src/guide/essentials/component-basics.md

resolves #360
Cherry picked from https://github.com/vuejs/docs/commit/9fcf20b1c4dcc34fd30308cc558a0bfbbcd77235

fix: missing comma (#360)

---

src/sponsor/index.md

resolves #371
Cherry picked from https://github.com/vuejs/docs/commit/96f22534f7f627941728be4816a3eb37655cb161

fix sponsor tier amouint (#371)

---

.github/contributing/writing-guide.md

resolves #374
Cherry picked from https://github.com/vuejs/docs/commit/838b67213ede05e5d5fc389d025b7905673d6f89

Fix a link (#374)

---

src/tutorial/src/step-11/description.md

resolve https://github.com/vuejs-translations/docs-ja/issues/87
https://vuejs.org/tutorial/#step-11 を翻訳しました。
レビューお願いします 🙏

「Tutorial > Components」の翻訳

---

src/api/reactivity-utilities.md

resolves #393
Cherry picked from https://github.com/vuejs/docs/commit/0f69aba14027de139617e2f8d364cfdbfee80163

Update API entry for toRef to mention mutating props (#393)

---

src/guide/essentials/reactivity-fundamentals.md

resolve #391
vuejs/docs@81bf41c の反映です

fix: small typo

---

src/api/composition-api-setup.md

resolve #395
vuejs/docs@4b0f9c9 の反映です

Fix broken 'ref-unwrapping-in-templates' link to

---

src/guide/built-ins/transition.md

resolves #402
Cherry picked from https://github.com/vuejs/docs/commit/dcced411a8c8f3a6fea310efdc788ab7a320b3a5

Fixes typo (#402)

---

src/guide/extras/render-function.md

resolves #408
Cherry picked from https://github.com/vuejs/docs/commit/3d0fa5662614f76ead1136c4fe631ad0f97c1e68

fix typo (#408)

---

src/examples/src/cells/Cell/template.html
src/examples/src/circle-drawer/App/composition.js
src/examples/src/circle-drawer/App/template.html
src/examples/src/flight-booker/App/template.html
src/examples/src/form-bindings/App/template.html
src/examples/src/timer/App/template.html
src/examples/src/todomvc/App/template.html

resolves #411
Cherry picked from https://github.com/vuejs/docs/commit/ee525296e69943da8d8f4d5211024de15f513aee

Fix examples in HTML mode (#411)

---

src/guide/typescript/composition-api.md

resolve #407
vuejs/docs@0f893e7 の反映です

fix: add h3 in src/guide/typescript/composition-api.md

---

src/tutorial/src/step-9/description.md

resolves #99
お手すきにレビューおねがいいたします。

Translate Tutorial > Lifecycle and Template Refs

---

src/guide/components/provide-inject.md
src/guide/typescript/options-api.md

resolves #420
Cherry picked from https://github.com/vuejs/docs/commit/1c69ce063402bc1e9d8671aa9a245b77f39a152f

fix: fix a typo (#420)

---

src/guide/components/provide-inject.md
src/guide/scaling-up/state-management.md
src/guide/typescript/options-api.md

resolves #422
Cherry picked from https://github.com/vuejs/docs/commit/4474c1f707f41ee73a62b3019baace4c6eb3a251

fix: remove obtrusive punctuation marks (#422)

---

.vitepress/config.ts
src/guide/essentials/event-handling.md
src/guide/typescript/options-api.md

docs: translate TypeScript options api

---

src/api/render-function.md

resolves #439
Cherry picked from https://github.com/vuejs/docs/commit/cdafa0f34802709b9b0c7a7ec72cd24daed2eba1

Update render-function.md (#439)

---

src/about/team/TeamPage.vue

resolve #110 
PR作成お待たせいたしました。
ご確認よろしくお願いいたします。
意訳した箇所が多いです。

Translate "About > Meet the Team"

---

src/api/built-in-components.md
src/guide/quick-start.md

resolves #441
Cherry picked from https://github.com/vuejs/docs/commit/42e733f35942c14b9e42a138c12c0743cb699b77

chore: fix typos (#441)

---

src/guide/typescript/composition-api.md
src/guide/typescript/options-api.md

resolves #445
Cherry picked from https://github.com/vuejs/docs/commit/4fc8ad3c89fb243b7b19b871381b2b44b088ddf1

Use 'import type' in TypeScript examples (#445)

---

src/api/application.md

resolves #458
Cherry picked from https://github.com/vuejs/docs/commit/38748a28b62dbd15b7a53b2971b17358e56039a2

fix link error (#458)

---

.vitepress/config.ts

resolves #460
Cherry picked from https://github.com/vuejs/docs/commit/02b38bd06fb730dac6b9fe70ee3cda036cbfd06a

feat: added links to core libraries (#460)

---

README.md
src/tutorial/src/step-11/description.md

Update README.md and fix a typo

---

src/guide/built-ins/keep-alive.md

resolves #467
Cherry picked from https://github.com/vuejs/docs/commit/62af1da18a4dc26362519690a79d421e93b1d7ff

docs: self-close dynamic `component` for consistency (#467)

---

.vitepress/config.ts
src/ecosystem/partners.md
src/ecosystem/video-courses.md

resolves #469
Cherry picked from https://github.com/vuejs/docs/commit/540ebdc598bc658982d17ea106ece4e27a690e03

adjust partners placing (#469)

---

src/api/ApiIndex.vue

resolves #481
Cherry picked from https://github.com/vuejs/docs/commit/5850147b43081756fc026dabeb60f3f8442c687e

Fix inconsistent column layout between browsers (#481)

---

.vitepress/theme/components/VueSchoolBanner.vue
src/api/ApiIndex.vue
src/api/built-in-components.md
src/api/reactivity-utilities.md

resolves #487
Cherry picked from https://github.com/vuejs/docs/commit/62caca6be4c8a5b5c4b88773090d819eefad4a9b

fix: banner height error (#487)

---

.vitepress/theme/components/VueSchoolBanner.vue

resolves #496
Cherry picked from https://github.com/vuejs/docs/commit/67db2a54378a9978755a9c1d810a99115c4a7c1f

Update Vue School banner copy (#496)

---

src/api/composition-api-setup.md

resolve #416
本家とsyncするための修正です。
> New updates on head repo.
> https://github.com/vuejs/docs/commit/59913b578d63dbe352c04a7002a9748b8a051581

本家とsyncするため修正

---

src/about/community-guide.md

resolves #510
Cherry picked from https://github.com/vuejs/docs/commit/17ac0ef89d957467736f27b332994f57db4129a5

updated twitter community to the community-guide (#510)

---

src/partners/components/PartnerCard.vue

resolve #477
https://github.com/vuejs/docs/commit/7b3af645972a9b677cff0dcb6e9ab9113bbcb395 の反映です

fix partners dark mode logo css

---

src/partners/components/PartnerCard.vue
src/partners/components/PartnerLanding.vue

resolve #478
vuejs/docs@b1adf6d の反映です

partner style tweaks

---

.github/CONTRIBUTING.md

差分 issue が増えてきており、対応してくださる方も出てきたのでコメントアウトを外して内容を微調整しました

ページ翻訳以外の貢献方法を追加

---

src/partners/partners.json

resolve #506
vuejs/docs@355bbcd の反映です

update vehikl partner info

---

package.json
pnpm-lock.yaml

resolve #523
vuejs/docs@384166b の反映です

bump vitepress

---

.vitepress/config.ts

resolves #544
Cherry picked from https://github.com/vuejs/docs/commit/33ecb455688a05aa66e3a2f53caceb44cef2f7f5

replace forum with github discussions link (#544)

---

src/api/application.md

resolves #546
Cherry picked from https://github.com/vuejs/docs/commit/732633c05a8486edeb9ee02ca8ac43acb8060053

Grammar tweaks to application.md (#546)

---

src/api/application.md
src/api/options-state.md

resolves #548
Cherry picked from https://github.com/vuejs/docs/commit/43090492923711ff8463e1b6fddf8cbbb0a6c405

Update api/options-state.md (#548)

---

src/guide/scaling-up/testing.md

resolves #555
Cherry picked from https://github.com/vuejs/docs/commit/fec462f27f853aaf8f70638887f08c495c378dc3

add closing parentheses (#555)

---

src/api/ssr.md
src/guide/scaling-up/ssr.md

resolves #561
Cherry picked from https://github.com/vuejs/docs/commit/ff3d24a23794ad208a1a686c963e23e874a74e08

update ssr teleport usage (#561)

---

src/guide/components/slots.md

resolves #564
Cherry picked from https://github.com/vuejs/docs/commit/ce8b3449683ef5d24efe351320beeab1e8dfaa5b

Fix grammar (#564)

---

src/tutorial/src/step-2/description.md

resolves #570
Cherry picked from https://github.com/vuejs/docs/commit/ec3630d3a62e870b53d68e1487b4739d36d5830c

fix: fixed typo in tutorial step-2 (#570)

---

src/about/team/members-partner.json

resolves #574
Cherry picked from https://github.com/vuejs/docs/commit/c1927df108da229060df3d4e9fc747dd0dd01974

chore: update Erick Petrucelli information (#574)

---

src/examples/utils.ts

resolves #580
Cherry picked from https://github.com/vuejs/docs/commit/3a54e46dbc886baf5e250e3a1e28c982ad21aa17

Fixed rendering about ending lines in example desc (#580)

---

src/api/ApiIndex.vue
src/api/api.data.ts

resolves #599
Cherry picked from https://github.com/vuejs/docs/commit/3491a8384eefe83170939f96155f7e60af1a9554

supported custom anchors in API index (#599)

---

src/api/application.md

resolves #625
Cherry picked from https://github.com/vuejs/docs/commit/9050e7fd3fc6ed0f8da80bf81b78ace30ab1e78a

perfect: Add missing fields (#625)

---

src/guide/quick-start.md

resolve #543
vuejs/docs@680d4a0 の反映と翻訳です

update import maps support information

---

src/guide/scaling-up/ssr.md

resolve #560
vuejs/docs@83a46e1 の反映です

fix ssr example link

---

src/guide/essentials/event-handling.md

resolve #578
vuejs/docs@a83ffeb の反映です

Fix a link

---

src/guide/extras/reactivity-in-depth.md
src/guide/extras/rendering-mechanism.md

resolves #617
Cherry picked from https://github.com/vuejs/docs/commit/b9c157fc5f8f03e6dec17a9b26acc943cb99bcbb

Reorder reactivity pseudo-code (#617)

---

src/guide/extras/reactivity-in-depth.md
src/guide/extras/rendering-mechanism.md
src/tutorial/TutorialRepl.vue

resolves #619
Cherry picked from https://github.com/vuejs/docs/commit/a4761cd61c02d2cf76bdeaa154dc28241bbefe31

fix: tutorial breaks the back button (#619)

---

.vitepress/theme/index.ts

resolves #null
Cherry picked from https://github.com/vuejs/docs/commit/5281fd3f345bed7dbbd1f344b73b0a2699de885f

add missing component 

---

src/api/component-instance.md

resolves #699
Cherry picked from https://github.com/vuejs/docs/commit/f10655a3574d4ab486c4de4e3692bf18f57833c7

Fixed small typo (#699)

---

src/guide/essentials/component-basics.md

resolve #577
vuejs/docs@7a1130a の取り込みです

docs: expand component-basics.md with emits

---

src/guide/typescript/options-api.md

resolve #579
vuejs/docs@ffb375e の取り込みです

Add more specific example code to Type Augmentation docs.

---

src/guide/quick-start.md
src/guide/scaling-up/tooling.md

resolve #582
vuejs/docs@58b4470 の取り込みです

update IDE support info

---

src/api/ApiIndex.vue
src/api/api.data.ts

resolve #604
vuejs/docs@98b7484 の取り込みです

fixed API filter bug

---

src/guide/built-ins/transition-group.md

resolve #615
vuejs/docs@c3bb74b の反映です

Note the use of GreenSock in an example

---

package.json
pnpm-lock.yaml

resolve #622
vuejs/docs@bf872f3 の反映です

bump vue + repl

---

src/guide/typescript/overview.md

resolve #623
vuejs/docs@e3551d1 の反映です

update vue-tsc usage

---

src/guide/components/events.md
src/guide/essentials/component-basics.md

resolve #612
https://github.com/vuejs/docs/commit/a4c027ff9ee4dfd338b6687f03c5efa3d47a542f の対応です

docs: various tweaks to how events are documented

---

src/guide/scaling-up/ssr.md

resolve #563
翻訳後に追加されたパートの対応です

「Guide > Scaling Up > Server-Side Rendering (SSR) > Teleports パート」の翻訳

---

src/guide/quick-start.md

resolve #641
vuejs/docs@27497fa の反映です

Add a note about Composition API usage to Quick Start

---

src/api/built-in-directives.md
src/guide/essentials/class-and-style.md
src/guide/essentials/list.md

resolve #642
vuejs/docs@fd0ee9f の反映です

use consistent component casing

---

src/guide/components/async.md

resolve #645
vuejs/docs@fb76958 の反映です

Extend the examples for async components

---

src/api/sfc-script-setup.md

（ryu-cho が反応しなかったようで該当 issue なし）
vuejs/docs@7ab3991 の反映です

fix: added export as TS workaround

---

.vitepress/config.ts

resolves #723
Cherry picked from https://github.com/vuejs/docs/commit/e575e79890bb53b5819e8933b441f14b13c43502

Adding meta theme-color (#723)

---

package.json
pnpm-lock.yaml

resolve #669
vuejs/docs@9028c70 の反映です

bump theme

---

src/about/team/TeamList.vue

resolves #740
Cherry picked from https://github.com/vuejs/docs/commit/32515361dbd720065fb631a058ba232e90bbe31c

Fix wrong shuffled team members info (#740)

---

src/partners/partners.json

resolves #743
Cherry picked from https://github.com/vuejs/docs/commit/f0c7086c485f229009ce315629b30822ff61691a

Fix hiring link (#743)

---

src/translations/index.md

resolves #763
Cherry picked from https://github.com/vuejs/docs/commit/cad28891349bd26cc394103c7db155adc4c54d2f

Update index.md (#763)

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/SponsorsGroup.vue
.vitepress/theme/components/sponsors.ts

resolve #694
vuejs/docs@abd953b の反映です
（ランタイムエラーが出ていますが、本家も同様なのでとりいそぎそのままにしてあります）

Support dynamic loading of special sponsors

---

src/guide/typescript/options-api.md

resolve #702 
vuejs/docs@58844c0 の反映です

Fix Caveats about props in TS with Options API

---

src/guide/reusability/custom-directives.md

resolve #708
vuejs/docs@a77f9e2 の反映です

fix: mentioned arguments in all directive hooks

---

.vitepress/config.ts

resolves #765
Cherry picked from https://github.com/vuejs/docs/commit/ebab2325755f3c6e29cf0b13b32f7d2936593cc6

tweak ecosystem dropdown (#765)

---

src/about/team/TeamPage.vue

resolve #737
vuejs/docs@ffe760d の反映です

Shuffle team members

---

src/partners/components/PartnerList.vue

resolves #772
Cherry picked from https://github.com/vuejs/docs/commit/c03d02bd571c22d27035e6ec29ba01a55ac728ed

randomize partners display order (#772)

---

src/about/team/members-partner.json

resolves #782
Cherry picked from https://github.com/vuejs/docs/commit/c991f6d6468157bc46aa15147eef0be80a4aa540

fix wrong url (#782)

---

src/partners/components/PartnerList.vue

resolve #774
vuejs/docs@e95ddf3 の反映です

ensure platinum partners are listed first

---

.vitepress/theme/components/Home.vue

resolves #796
Cherry picked from https://github.com/vuejs/docs/commit/4febb7c12f5c085dfd4c63544adfe8719ee15500

special sponsor mobile style fix (#796)

---

.vitepress/theme/components/Home.vue

resolves #798
Cherry picked from https://github.com/vuejs/docs/commit/ad4bb2fb7f21e68cd0f50298f39b2c0b67a31d4e

special sponsor mobile style fix (#798)

---

src/guide/extras/reactivity-in-depth.md

resolve #785
vuejs/docs@411160e の反映です

chore: add spaces around slash

---

src/partners/partners.json

resolves #813
Cherry picked from https://github.com/vuejs/docs/commit/efac9121d0a4ae9137e8cdce09a429db5f7e80a4

update activelogic contact email (#813)

---

src/api/component-instance.md
src/api/options-state.md
src/api/reactivity-core.md

resolve #786
vuejs/docs@93d4aa6 の反映です

Add a note about `flush: 'sync'`, with links from elsewhere

---

src/guide/best-practices/performance.md

resolve #787
vuejs/docs@9a6021d の反映です

Update the note about Vue Router and lazy loading

---

src/guide/scaling-up/testing.md

resolve #788
vuejs/docs@ac20109 の反映です

Fix Testing Library example

---

src/guide/extras/composition-api-faq.md

resolve #789
vuejs/docs@6108389 の反映です

Composition api is available in Vue 2.7

---

package.json
pnpm-lock.yaml
src/examples/index.md
src/guide/introduction.md
src/index.md
src/sponsor/index.md
src/tutorial/TutorialRepl.vue
src/tutorial/index.md
src/tutorial/tutorial.data.ts
tsconfig.json

resolve #800 
vuejs/docs@f54aab3 の反映です

upgrade to vitepress v1

---

.vitepress/config.ts
.vitepress/jobsMdPlugin.ts
.vitepress/theme/components/VueJobs.vue
.vitepress/theme/index.ts
src/sponsor/index.md

resolves #816
Cherry picked from https://github.com/vuejs/docs/commit/b925d8ac0a17e4ab38f1df90331215667bde3a32

Move VueJobs widget to page headings (#816)

---

.vitepress/jobsMdPlugin.ts

resolves #819
Cherry picked from https://github.com/vuejs/docs/commit/74449a840c88ee9488e2337081302a993e14e1f6

exclude sponsor page for ad injection (#819)

---

src/guide/extras/animation.md

resolves #825
Cherry picked from https://github.com/vuejs/docs/commit/9cac663ff01b50532c5a77cf8405058ecf954293

Adjust an example template in animation.md (#825)

---

src/api/options-state.md

resolves #839
Cherry picked from https://github.com/vuejs/docs/commit/94f483e4ac4111b1b1f9e20c2f5af6bb1b8b16b3

Fix grammar mistake (#839)

---

src/guide/typescript/composition-api.md

resolve #824
vuejs/docs@a63c429 の反映です

Update link to Takeover Mode

---

.vitepress/config.ts
.vitepress/headerMdPlugin.ts
.vitepress/jobsMdPlugin.ts
.vitepress/theme/components/preferences.ts
package.json
pnpm-lock.yaml

resolve #832
vuejs/docs@814a9b3 の反映です

adapt vitepress alpha.12

---

package.json
pnpm-lock.yaml
src/tutorial/TutorialRepl.vue
src/tutorial/tutorial.data.ts

resolve #831
vuejs/docs@169347a の反映です

fix tutorial highlighting

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #858
Cherry picked from https://github.com/vuejs/docs/commit/b2d3a52f63e293168037afdaaf4ef3af37373899

remove banner (#858)

---

src/guide/typescript/composition-api.md

resolve #853 
vuejs/docs@b392b06 の反映です

Added `withDefaults` to Composition API TypeScript page

---

src/guide/quick-start.md

resolve #860 resolve #861
vuejs/docs@6400d16 と vuejs/docs@2115610 の反映です

rewrite quick start

---

.vitepress/config.ts
src/api/reactivity-advanced.md

「API > Composition API > Reactivity API: Advanced」の翻訳

---

src/api/options-lifecycle.md

resolves #873
Cherry picked from https://github.com/vuejs/docs/commit/6d2dc93fdb742eff2a63fc5cf6dc5b4a385fe585

add notes in lifecycle hooks (#873)

---

.vitepress/config.ts
src/api/composition-api-lifecycle.md
src/api/reactivity-advanced.md

「API > Composition API > Composition API: Lifecycle Hooks」の翻訳

---

package.json
pnpm-lock.yaml

resolve #878
vuejs/docs@12d36c9 の反映です

bump repl, fix example & tutorial in Safari

---

.vitepress/config.ts
src/api/options-composition.md

「API > Options API > Options: Composition」の翻訳

---

.vitepress/config.ts
src/api/options-misc.md

「API > Options API > Options: Misc」の翻訳

---

src/translations/index.md

resolves #903
Cherry picked from https://github.com/vuejs/docs/commit/dbfbc7235291f0dd8af88c6f6edf4d87e13f2053

update translation page: add link to source, add Ukrainian wip entry (#903)

---

.vitepress/config.ts
src/api/component-instance.md
src/guide/extras/render-function.md

「API > Options API > Component Instance」の翻訳

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #909
Cherry picked from https://github.com/vuejs/docs/commit/3d6ddcbcef182feb1ac8d0eda39f480656cea890

Add vue toronto banner (#909)

---

src/tutorial/TutorialRepl.vue

resolves #911
Cherry picked from https://github.com/vuejs/docs/commit/9fc32de5b5a5c9d619fcaaadc429823e69c4d5cc

just removing nonexistent module. (#911)

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

resolves #927
Cherry picked from https://github.com/vuejs/docs/commit/ee975453c0e4547831123051b4b1645f967fc926

Change text to reflect remote event (#927)

---

.vitepress/theme/components/VueJobs.vue
src/about/team/TeamList.vue

resolves #935
Cherry picked from https://github.com/vuejs/docs/commit/7e9f1e642b48de5cfd412d0fb932209181124599

fix: TeamList.vue sticky info (#935)

---

src/guide/scaling-up/tooling.md

No related issue as this is just a typo fix

fix typo: Volor to Volar

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #943
Cherry picked from https://github.com/vuejs/docs/commit/73661d8ee6d486a830130870032ac06ee1ab06c4

remove vue toronto banner (#943)

---

src/about/team/TeamList.vue

resolves #949
Cherry picked from https://github.com/vuejs/docs/commit/92df83d857189157ee1f1094ad0c4b50337e38da

Fix Team sticky headers (#949)

---

src/api/reactivity-utilities.md

resolve #953
vuejs/docs@381861a の反映です

Add computed refs to isReadonly

---

src/guide/essentials/watchers.md

watchers.md 未翻訳箇所の対応

---

src/api/ApiIndex.vue
src/api/api.data.ts

resolves #974
Cherry picked from https://github.com/vuejs/docs/commit/11bd76fa9a3e01cea60257af77c23645fcb4008d

Fix API index heading text (#974)

---

.vitepress/config.ts
src/api/built-in-special-elements.md

「API > Built-ins > Special Elements」の翻訳

---

src/about/faq.md

resolves #979
Cherry picked from https://github.com/vuejs/docs/commit/460f55a1324b904eb9446534aa7599319765c789

FAQ tweaks (#979)

---

.vitepress/theme/components/VueMasteryBanner.vue

resolves #977
Cherry picked from https://github.com/vuejs/docs/commit/07dcd19880f01419b3c84d7e2cbf31b80bba5b9c

vue mastery banner mobile fix (#977)

---

src/about/team/members-core.json

resolves #983
Cherry picked from https://github.com/vuejs/docs/commit/2f436c6451974c45195738fe10f7ef3b69ce7bf6

chore: update team member (#983)

---

src/about/team/members-core.json
src/translations/index.md

resolves #985
Cherry picked from https://github.com/vuejs/docs/commit/9e0fc14876175332a4de043a47cdd43e68ead0bb

feat: add french translations repo link (#985)

---

src/about/team/members-partner.json

resolves #989
Cherry picked from https://github.com/vuejs/docs/commit/117f19329a4983e992e808c7a07acedee7251925

chore: update partner's company after rebranding (#989)

---

.vitepress/config.ts
src/api/built-in-special-attributes.md

「API > Built-ins > Special Attributes」の翻訳

---

src/partners/partners.json

resolves #997
Cherry picked from https://github.com/vuejs/docs/commit/f42130066dbdd0f49b2a0d25965dfd65fe84e814

update jump24 url (#997)

---

.vitepress/config.ts
src/api/sfc-spec.md

「API > Single File Component > SFC Syntax Specification」の翻訳

---

.vitepress/config.ts
src/api/built-in-directives.md
src/api/sfc-css-features.md
src/style-guide/rules-essential.md

「API > Single File Component > SFC CSS Features」の翻訳

---

src/api/composition-api-setup.md

resolve #1016
vuejs/docs@8bb7480 の反映です

Added a warning regarding async setup

---

.vitepress/config.ts
src/api/custom-renderer.md

resolve #83 
よろしくお願いします！:pray:

「API > Advanced APIs > Custom Renderer API」の翻訳

---

src/about/team/members-core.json

resolves #1022
Cherry picked from https://github.com/vuejs/docs/commit/051d926a4bcafd9037d7e1a650725e19bf044fd3

Fix broken portal-vue link (#1022)

---

src/sponsor/index.md

resolve #113
よろしくお願いします！:pray:

「Sponsor > Become a Vue.js Sponsor」の翻訳

---

src/api/api.data.ts

resolves #1046
Cherry picked from https://github.com/vuejs/docs/commit/262b5a17b324bc82567fbe4fa1c8abd90e7fb458

Removed unnecessary escape character (#1046)

---

src/api/utility-types.md

resolves #1052
Cherry picked from https://github.com/vuejs/docs/commit/30e1a70d674ee87d229cbdca7615b458dfecd225

Update utility-types.md (#1052)

---

.vitepress/theme/components/PreferenceSwitch.vue
src/style-guide/rules-essential.md

resolve #1033 
vuejs/docs@bea9c1d の反映です

Fix-styleguide-1

---

src/guide/essentials/template-refs.md
src/guide/typescript/composition-api.md

resolve #1043
vuejs/docs@f634c9b の反映です

Add a comment about not importing defineExpose

---

src/api/built-in-special-attributes.md
src/api/composition-api-dependency-injection.md
src/api/options-state.md
src/api/reactivity-core.md
src/guide/typescript/options-api.md

resolve #1045
vuejs/docs@d880833 の反映です

Links to TS docs from the API section

---

.vitepress/config.ts
src/about/community-guide.md

resolve #107 
よろしくお願いします！:pray:

「About > Community Guide」の翻訳

---

.vitepress/config.ts
.vitepress/theme/index.ts

resolves #1056
Cherry picked from https://github.com/vuejs/docs/commit/0fc28808ee113261ea0b5bc050b1a36eb5b97549

Disable VueJobs widget (#1056)

---

.vitepress/theme/components/SponsorsGroup.vue
.vitepress/theme/components/VueJobs.vue
.vitepress/theme/styles/vue-mastery.css
src/about/team/TeamHero.vue
src/guide/built-ins/keep-alive-demos/CompA.vue
src/guide/built-ins/keep-alive-demos/CompB.vue
src/guide/built-ins/transition-demos/CssAnimation.vue
src/guide/extras/demos/SpreadSheet.vue
src/guide/scaling-up/TestingApiSwitcher.vue

resolves #1065
Cherry picked from https://github.com/vuejs/docs/commit/6ba82704a3919bb9d117a31d7fbf61080652a887

Minor changes suggested by Prettier (#1065)

---

src/api/sfc-spec.md

resolve #1054
vuejs/docs@a35b5de の反映です

Fix casing of Sass

---

src/api/built-in-special-elements.md
src/guide/essentials/conditional.md

resolve #1061
vuejs/docs@9dd81cd の反映です

Add an API entry for `<template>`

---

src/examples/src/modal/Modal/style.css
src/examples/src/modal/Modal/template.html

resolves #1079
Cherry picked from https://github.com/vuejs/docs/commit/196e817fd150e93cf1393c00eb4068e4a273e824

Fix the modal example transition in Firefox (#1079)

---

src/guide/scaling-up/sfc.md

resolve #1064
vuejs/docs@10bfe93 の反映です

Composition API example of SFC

---

src/guide/components/events.md

resolve #1067
vuejs/docs@7b8e101 の反映です
（別の PR で同じファイルを変更したので上記の diff とは行番号がずれています）

Reword the opening sentence about declaring events

---

src/about/team/members-core.json
src/about/team/members-emeriti.json

resolves #1087
Cherry picked from https://github.com/vuejs/docs/commit/812dca474fa849502a97cb3552acd4ff0138787e

move Damian to emeriti (#1087)

---

src/guide/typescript/composition-api.md

resolve #1070 
vuejs/docs@a679e81 の反映です

Document PropType usage with the Composition API

---

src/guide/essentials/watchers.md

resolve #1077
vuejs/docs@80d2eb5 の反映です

Add a clarifying comment to a watcher example

---

.vitepress/config.ts
.vitepress/theme/components/Home.vue

resolve #1086
vuejs/docs@124a5f7 の反映です

remove newsletter links

---

src/guide/components/provide-inject.md

resolve #1095
vuejs/docs@b589d97 の反映です

Fix wording

---

src/api/reactivity-core.md

resolve #1068
vuejs/docs@7295166 の反映です

Add more API examples for `watch()`

---

.vitepress/theme/components/SponsorsGroup.vue
.vitepress/theme/components/sponsors.ts
src/partners/components/PartnerCard.vue
src/partners/components/PartnerPage.vue

resolve #1101
vuejs/docs@95de4cb の反映です

setup analytics for sponsor/partner links

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/SiteMap.vue

resolve #1096
vuejs/docs@86d0a38 の反映です

add a bottom nav

---

src/guide/components/v-model.md
src/guide/reusability/plugins.md
src/guide/typescript/composition-api.md

resolve #1112
vuejs/docs@817b53e の反映です
- `src/api/general.md` は #1104 で対応済み
- `src/ecosystem/newsletters.md` は #1109 で対応

chore: add missing anchors

---

src/ecosystem/themes/themes.json

resolves #1116
Cherry picked from https://github.com/vuejs/docs/commit/24a53b96e2b74b73ef839fab94b7e6e809890092

Apollo-Vue order changed and text fixes (#1116)

---

src/ecosystem/themes/ThemePage.vue

resolves #1121
Cherry picked from https://github.com/vuejs/docs/commit/b193a138f839255aac0f58a503c47a3cbe20b6b2

fix: typo (#1121)

---

src/guide/best-practices/accessibility.md

resolves #1130
Cherry picked from https://github.com/vuejs/docs/commit/c978453288f9007614d2bd59f8cb09f6bd90555a

docs: fix aria-labelledby example. (#1130)

---

src/partners/partners.json

resolves #1132
Cherry picked from https://github.com/vuejs/docs/commit/db62d3ceb81b31365a1d86d56d795787a5e9e751

update monterail url (#1132)

---

src/ecosystem/themes/themes.json

resolves #1136
Cherry picked from https://github.com/vuejs/docs/commit/198a796d6672acab28f4e9d0922fcde8d5c3ff8c

fix: typo (#1136)

---

src/guide/typescript/composition-api.md

resolve #1142 
vuejs/docs@7e2f358 の反映です

Revert "docs: fix Prop interface type error in example

---

src/guide/introduction.md

resolves #1144
Cherry picked from https://github.com/vuejs/docs/commit/38b3baa90ea02437983e138ad08db89096171f6d

Fix Vue Mastery link (#1144)

---

src/partners/partners.json

resolves #1146
Cherry picked from https://github.com/vuejs/docs/commit/1cd64a882ad0be60728baffa16188e70935bcdba

epicmax -> platinum (#1146)

---

src/partners/components/PartnerLanding.vue
src/partners/components/PartnerList.vue

resolves #1148
Cherry picked from https://github.com/vuejs/docs/commit/e2c54b9b9d66a6e267e42ac55e3098bd46c35eee

improve all partner listing (#1148)

---

src/translations/index.md

resolves #1153
Cherry picked from https://github.com/vuejs/docs/commit/67f81a02784778f7fd8710329cb968f349f859e3

update french translation URL (#1153)

---

src/guide/extras/composition-api-faq.md

resolve #1150
vuejs/docs@4f2e4ce の反映です

Add link to Vue School video lesson

---

src/about/faq.md
src/guide/components/registration.md

「About > Frequently Asked Questions」の翻訳

---

src/style-guide/rules-strongly-recommended.md

resolve #1118 resolve #1127
vuejs/docs@87c98a3, vuejs/docs@71247b5 の反映です

Fix styleguide - part 2

---

src/guide/extras/composition-api-faq.md

resolve #1156
vuejs/docs@a3eb853 の反映です

Fix broken link

---

src/about/team/members-core.json

resolve #1157 
vuejs/docs@ead4aa2 の反映です

update references to volar

---

src/guide/essentials/reactivity-fundamentals.md

resolve #1159
vuejs/docs@25d30c5 の反映です

fix(reactivity): template render result

---

.vitepress/theme/components/SiteMap.vue

resolves #1165
Cherry picked from https://github.com/vuejs/docs/commit/93caf53cdeff5ac3e16b91bb75bc356a38d330a2

Make SiteMap.vue compatible with translations (#1165)

---

src/guide/quick-start.md

resolve #1164
vuejs/docs@8df5f60 の反映です

docs: update not about firefox support for import maps

---

src/guide/typescript/overview.md

resolve #1175
vuejs/docs@f4ff204 の反映です

Fix reference to `defineComponent` type tests

---

src/guide/scaling-up/tooling.md

resolve #1181
vuejs/docs@4895c57 の反映です

Fix vue-tsc link

---

src/guide/extras/rendering-mechanism.md

resolve #1191
vuejs/docs@5cc0b37 の反映です

fix: remove netlify template explorer link

---

src/ecosystem/themes/ThemeListItem.vue
src/ecosystem/themes/ThemePage.vue

resolve #112 
`themes.json` はそのままにしてあります

「Ecosystem > Themes」の翻訳

---

src/api/composition-api-setup.md

resolve #1178
vuejs/docs@8f9e959 の反映です

ensure script setup recommendation can be seen when linked from api page

---

src/translations/index.md

https://ja.vuejs.org/translations/ の翻訳です
（issue 作成漏れ）

「Translations」の翻訳

---

src/guide/extras/reactivity-in-depth.md

resolve #1189 
vuejs/docs@51a019c の反映です

add section on connection to signals

---

.vitepress/config.ts
src/guide/extras/reactivity-transform.md

resolve #1195
vuejs/docs@bb3469c の反映です

deprecate Reactivity Transform

---

.vitepress/config.ts

resolves #1206
Cherry picked from https://github.com/vuejs/docs/commit/a99051399c89630bd00383161995274e9afa26a9

remove unused title for Custom Renderer (#1206)

---

src/about/faq.md

全角と半角の間にスペース追加

---

src/partners/partners.json

resolves #1212
Cherry picked from https://github.com/vuejs/docs/commit/634ad1f444278b75adac6ec8f4390ab2a1a40079

update parnter info (#1212)

---

src/guide/extras/reactivity-in-depth.md

resolve #1200 resolve #1201 resolve #1211
vuejs/docs@d0bd349, vuejs/docs@f64cf09, vuejs/docs@e1df70d の反映です

update to signals section

---

package.json

resolve #1222
vuejs/docs@a19d4a6 の反映です

chore: use preview instead of serve command

---

src/partners/partners.json

resolves #1235
Cherry picked from https://github.com/vuejs/docs/commit/14509cb543e7171ae40712223d0baaae3850ba75

partner edits (#1235)

---

package.json
pnpm-lock.yaml

resolve #1234 resolve #1239
vuejs/docs@630692a, vuejs/docs@6ae943f の反映です

bump vitepress + theme

---

src/guide/built-ins/transition-demos/ListStagger.vue

resolves #1247
Cherry picked from https://github.com/vuejs/docs/commit/09edd7a8fa8de23b2e021241dd7347e2f17b4f66

Fix staggered list transition demo (#1247)

---

src/guide/extras/demos/ElasticHeader.vue

resolves #1254
Cherry picked from https://github.com/vuejs/docs/commit/8cfefd272ed4333e8d0e8cf41743b12b8affea5d

Fix animated ElasticHeader demo (#1254)

---

src/api/sfc-spec.md

resolve #1257
vuejs/docs@d209fc7 の反映です

Remove excess words and fix minor language issues

---

.vitepress/config.ts
package.json
pnpm-lock.yaml

resolve #1258 resolve #1259 resolve #1261
vuejs/docs@36f2cff, vuejs/docs@b77752b, vuejs/docs@13280e5 の反映です

bump theme + vitepress

---

.vitepress/theme/components/Home.vue

resolves #1266
Cherry picked from https://github.com/vuejs/docs/commit/e7d19fbeeab13f5b93da1c51be634b12451ccde2

give special sponsor explicit size (#1266)

---

package.json
pnpm-lock.yaml
src/examples/ExampleRepl.vue
src/examples/index.md

resolve #1268
vuejs/docs@f1a3abc の反映です

bump theme + make example output button visible on mobile

---

.vitepress/config.ts
src/translations/index.md

resolve #1272 resolve #1278 
vuejs/docs@1faadee と vuejs/docs@0ecd513 の反映です

Change Ukrainian + French translation as completed

---

src/about/team/members-core.json

resolves #1294
Cherry picked from https://github.com/vuejs/docs/commit/074ba55b5e0b99f57f0785c697f8b348f279a6ac

chore: add brc-dd to core team (#1294)

---

src/api/ApiIndex.vue

resolves #1297
Cherry picked from https://github.com/vuejs/docs/commit/4a6edbf43edc1bb6dcda198ad2af804ccae4db25

fix: Update padding to improve layout consistency (#1297)

---

.vitepress/config.ts

resolve #1299 
vuejs/docs@42e8840 の反映です

Add link to official certification website

---

src/guide/typescript/composition-api.md

resolve #1274
vuejs/docs@de6053c の反映です

Using ComponentPublicInstance with template refs

---

.vitepress/theme/components/PreferenceSwitch.vue

翻訳ありがとうございます 🙇
API選択の ❓ のアンカーリンクを正しいものに修正しました

fix switch-link

---

src/guide/extras/render-function.md

resolve #1302
vuejs/docs@9c3c2f1 の反映です

Template refs in render functions

---

src/guide/typescript/composition-api.md
src/guide/typescript/options-api.md

resolve #1303
vuejs/docs@ac42b95 の反映です

Reword type assertions with events

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #1304
Cherry picked from https://github.com/vuejs/docs/commit/6eda606f5f3d9e0d7f1cb9af1d557a7a31d2b9cd

conf banner (#1304)

---

src/partners/partners.json

resolves #1306
Cherry picked from https://github.com/vuejs/docs/commit/447f7b909f41c1b1adc8e0d732df88bbce64400b

chore: remove partner (#1306)

---

src/guide/essentials/computed.md

翻訳ありがとうございます！
細かい修正ですが、[書き込み可能な 算出関数](https://ja.vuejs.org/guide/essentials/computed.html#writable-computed) のサンプルコード内に存在する 不要なセミコロン を削除しました

remove unnecessary semicolons in computed.md

---

src/guide/extras/render-function.md

resolve #1315
vuejs/docs@efe4dc8 の反映です

add missing anchor

---

src/guide/essentials/forms.md

resolve #1316
vuejs/docs@4a7b07c の反映です

feat: forms.md added docs references in tip note

---

src/partners/partners.json

resolves #1326
Cherry picked from https://github.com/vuejs/docs/commit/615cb39ef1413c86d3937eaed41b1b99c93a07e4

update tighten email (#1326)

---

src/guide/built-ins/transition-demos/ListStagger.vue

resolves #1328
Cherry picked from https://github.com/vuejs/docs/commit/3b2469f97038924f9a0a130c96d8512e64069b50

fix: non-case sensitive filtering (#1328)

---

.vitepress/theme/components/Banner.vue

resolves #1351
Cherry picked from https://github.com/vuejs/docs/commit/5b045c2229b5581298993ec41e888f163961b2b1

update banner (#1351)

---

src/api/general.md
src/api/sfc-script-setup.md
src/guide/typescript/overview.md

resolve #1344
vuejs/docs@4d31a88 の反映です

3.3: generic components

---

src/guide/extras/render-function.md
src/guide/typescript/overview.md

resolve #1345
https://github.com/vuejs/docs/commit/fc83501ea7fb0f62e32455f5f3404b37ce7c767e の翻訳です。

3.3: jsx changes

---

src/examples/src/timer/App/composition.js
src/examples/src/timer/App/options.js
src/examples/src/timer/App/template.html

resolves #1364
Cherry picked from https://github.com/vuejs/docs/commit/1a50977b961ecb29b6fcfd2214a415bce23dddd0

fix: can not stop calling the 'update' method when elapsed > duration, in the timer example. #2359 (#1364)

---

src/api/options-rendering.md

Update options-rendering.md( About title of slots )

---

src/api/reactivity-utilities.md

resolve #1339 
vuejs/docs@3011e40 の反映です

3.3: toRef

---

src/api/reactivity-utilities.md

resolve #1337
vuejs/docs@8bcbf1a の反映です

3.3: toValue

---

src/api/application.md

resolve #1336
vuejs/docs@da8c449 の反映です

3.3: app.runWithContext

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #1377
Cherry picked from https://github.com/vuejs/docs/commit/4a07ffb5330d6860842c8129d83ec020857713d4

remove banner (#1377)

---

src/guide/quick-start.md

resolve #1362 
https://github.com/vuejs/docs/commit/f618a3a50c2bb15720cf4ead4600acc5e4520ef3 の修正に対応しました。

Update project initialization steps in quick-start.md file #1362

---

.vitepress/config.ts
.vitepress/theme/index.ts

resolves #1381
Cherry picked from https://github.com/vuejs/docs/commit/e5671d23b44dba4896eb0171f82c54873cf75efa

remove text ad (#1381)

---

src/api/utility-types.md

resolve #1335
[vuejs/docs@`4e26585`](https://github.com/vuejs/docs/commit/4e2658532279a9366b2b3534c8260dd0e2491014)の修正に対応いたしました。

Update utility types

---

src/guide/essentials/template-syntax.md

resolve #1383
https://github.com/vuejs/docs/commit/02d0f702ec0b1a88e117875e6ab844d23b7f1dc4 の修正に対応しました。

Fix broken URL for a restricted list of globals

---

src/public/_headers

resolves #1395
Cherry picked from https://github.com/vuejs/docs/commit/226d98c4245adadb2b2bccecda0537e3071c7a00

update embed restriction headers (#1395)

---

src/api/ApiIndex.vue

resolves #1401
Cherry picked from https://github.com/vuejs/docs/commit/58c73dbaf395f728d40383d00118cfd2131018df

focus filter box when visiting api index (#1401)

---

.vitepress/theme/styles/index.css
package.json
pnpm-lock.yaml

resolve #1389 
https://github.com/vuejs/docs/commit/0da496c1be517c15a4ced251c20f86e380954040 の反映です

fix:the flyout menu height when it's overflowed

---

src/api/options-misc.md
src/guide/components/attrs.md
src/guide/extras/composition-api-faq.md

resolve #1391
vuejs/docs@0da5428 の反映です

feat: update composition-api-faq.md

---

src/guide/reusability/composables.md

resolve #1397
vuejs/docs@4e81585 の反映です

minor tweaks

---

src/ecosystem/themes/ThemeListItem.vue
src/ecosystem/themes/ThemeProduct.vue

resolves #1435
Cherry picked from https://github.com/vuejs/docs/commit/3bf5bb516acebd9c241243d1b648b61490fd1460

chore: use defineProps type syntax (#1435)

---

src/api/ApiIndex.vue
src/ecosystem/themes/ThemeListItem.vue
src/ecosystem/themes/ThemeProduct.vue

resolves #1437
Cherry picked from https://github.com/vuejs/docs/commit/aa8ae47655617706f11b6a41979c88444a398161

add base url support on api index page (#1437)

---

src/guide/essentials/reactivity-fundamentals.md
src/guide/quick-start.md

resolve #1403 resolve #1400 resolve #1410 resolve #1422 
vuejs/docs@cdd928d vuejs/docs@303cd6d vuejs/docs@9849d63 vuejs/docs@9f057d2 の反映です

Rewrite reactivity fundamentals CAPI to start with refs

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/PreferenceSwitch.vue
.vitepress/theme/components/PreferenceTooltip.vue
.vitepress/theme/components/preferences.ts
src/guide/introduction.md

resolve #1411
vuejs/docs@9df7e58 の反映です

API style switch enhancements

---

src/api/sfc-script-setup.md

resolve #1409
vuejs/docs@3bd47dd の反映です

docs(script-setup): updated outdated tip

---

package.json
pnpm-lock.yaml

resolves #1447
Cherry picked from https://github.com/vuejs/docs/commit/0f29a145dc85aee111a78e3eed360e07863db4c1

chore: bump repl (#1447)

---

src/tutorial/src/step-9/App/composition.js
src/tutorial/src/step-9/App/template.html
src/tutorial/src/step-9/_hint/App/composition.js
src/tutorial/src/step-9/_hint/App/options.js
src/tutorial/src/step-9/description.md

resolve #1416
vuejs/docs@e7561df の反映です

Replace the variable `p` with `pElementRef`

---

src/guide/components/props.md

resolve #1426 
vuejs/docs@3f4e35c の反映です

Improve boolean casting example

---

src/guide/typescript/composition-api.md

resolve #1433 
vuejs/docs@6a0a845 の反映です

Example for new defineEmit with types syntax.md

---

.vitepress/config.ts
src/glossary/index.md

resolve #1407 resolve #1450
vuejs/docs@cf2a663 vuejs/docs@e2f92e0 の反映です。
念のためレビューお願いします:pray:
差分はこちらが分かりと思います → https://github.com/vuejs-translations/docs-ja/pull/1451/commits/10a949fc6afdc64490c4c372c9408d6411682f82

Add a glossary

---

src/guide/extras/web-components.md

add guide to typecheck web components written with vue

---

src/guide/components/v-model.md

add example for multiple v-model with modifiers

---

src/public/_headers

resolves #1472
Cherry picked from https://github.com/vuejs/docs/commit/8c2e85232282980e2ea700565c786488528fb231

additional allow embed headers (#1472)

---

src/guide/reusability/composables.md

resolves #1476
Cherry picked from https://github.com/vuejs/docs/commit/fe15ed89b280d99de9b3950d6d1452a76455189d

docs: onBeforeUnmount to onUnmounted for consistency (#1476)

---

src/guide/extras/render-function.md

resolve #1446
vuejs/docs@dbc89dd の反映です

Add example for typing functional components

---

src/guide/components/v-model.md

resolves #1482
Cherry picked from https://github.com/vuejs/docs/commit/9b06c2f66464356864e9c3ddeb80c0f45ea213e3

remove unnecessary space (#1482)

---

src/guide/scaling-up/tooling.md

resolve #1449
vuejs/docs@ff263e7 の反映です

Link to Microsoft Edge extension page

---

src/guide/components/attrs.md

resolve #1486
vuejs/docs@f9e5233 の反映です

docs: remove duplicate defineOptions script setup example

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

Revert "CFP 募集広告 (#1460)"

---

src/examples/src/cells/Cell/template.html
src/guide/extras/demos/SpreadSheetCell.vue

resolves #1498
Cherry picked from https://github.com/vuejs/docs/commit/4ba12e46654b50d5a01d72584b1db92ecd8577f0

docs: change @vnode-mounted to @vue:mounted (#1498)

---

src/guide/extras/reactivity-transform.md

resolve #1490
vuejs/docs@ca5f159 の反映です

link to drop-reactivity-transform

---

src/about/faq.md

resolve #1497 
https://github.com/vuejs/docs/commit/d22496b0c687aae7b9a301aa2b2448d4f80dd2b2 の反映です

docs(faq): remove outdated information about considering to use vue 2

---

src/guide/built-ins/transition.md

resolve #1505
vuejs/docs@b4ddd44 の反映です

docs: transition hook add comment

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolve https://github.com/vuejs-jp/vuefes-2023/issues/401
チケット販売開始のお知らせを追加

Vue Fes Japan 2023 チケット広告

---

src/api/reactivity-core.md

resolve #1517 
vuejs/docs@70b4d5d の反映です

docs: fix removed anchor

---

src/partners/partners.json

resolves #1530
Cherry picked from https://github.com/vuejs/docs/commit/61e4f235c95203b4bb9862cce70d836a103d045b

fix: update monterail link (#1530)

---

src/guide/scaling-up/tooling.md

original: https://vuejs.org/guide/scaling-up/tooling.html#ide-support

fix(scaling-up): update IDE supporting

---

.vitepress/theme/components/SponsorsGroup.vue

resolve #1532
vuejs/docs@b017bc4 の反映です

feat: update SponsorsGroup.vue

---

src/partners/partners.json

resolves #1546
Cherry picked from https://github.com/vuejs/docs/commit/7fe90c50a624bdc3800b517408ddf2e824b86821

remove jump24 (#1546)

---

src/guide/typescript/overview.md

resolve #1536
vuejs/docs@7231b0b の反映です

docs: update IDE support page as WebStorm now supports Volar

---

src/examples/ExampleRepl.vue

resolves #1556
Cherry picked from https://github.com/vuejs/docs/commit/6d12f2c8b8f4170fe8c6dcf58196f339db699527

perf: remove `resize` event listener when `unmounted` (#1556)

---

.vitepress/config.ts
src/translations/index.md

resolve #1554
vuejs/docs@1ab68f6 の反映です

Add translation link for bn.vuejs.org

---

src/guide/typescript/composition-api.md

resolve #1569 
vuejs/docs@ead027b の反映です

add DOM interface info to Typing Template Refs

---

.vitepress/config.ts
src/translations/index.md

resolve #1584
vuejs/docs@a6fa35f の反映です

Italian translation ready to launch

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

resolve #1587 
vuejs/docs@71ecfd5 の反映です

Add Vue Toronto banner - schedule 2

---

pnpm-lock.yaml

Bump vue from 3.3.4 to 3.3.7

---

src/guide/reusability/composables.md

resolve #1593 
vuejs/docs@620fe6c の反映です

Update composable guide reset values

---

src/guide/essentials/watchers.md

resolve #1617 
vuejs/docs@c979157 の反映です

Fix `watch` examples

---

src/about/team/TeamMember.vue

resolves #1622
Cherry picked from https://github.com/vuejs/docs/commit/7b9eb9c043291a11552189cb416ecd5bd7aafc1f

imported and changed twitter icon to new logo (#1622)

---

.vitepress/config.ts

resolves #1626
Cherry picked from https://github.com/vuejs/docs/commit/8c16348aaf8c154d3bbcdcd5bba5a372a65d959d

chore: temporarily remove vueschool script (#1626)

---

src/guide/typescript/overview.md

resolve #1602
vuejs/docs@ea76103 の反映です

docs: update url for vue-tsc in overview.md

---

src/guide/components/registration.md

resolve #1608
vuejs/docs@666561e の反映です
（既存部分の Lint Fix も含む）

Remove the app constant name from the method name

---

src/tutorial/src/step-10/App/template.html

resolves #1638
Cherry picked from https://github.com/vuejs/docs/commit/8087e308a125fdb6ee723d2ca1254c5e94c8d33d

fix(tutorial): race condition on step-10 (#1638)

---

src/api/reactivity-core.md

resolves #1640
Cherry picked from https://github.com/vuejs/docs/commit/67f4d3a366baa96ea8edd66f36c21dcd4fdb6de7

fix: ref example (#1640)

---

.vitepress/theme/components/SponsorsGroup.vue

resolves #1644
Cherry picked from https://github.com/vuejs/docs/commit/07cac45939b8e5fbae5c89039ff1059c3bb7f112

fix aside special max height (#1644)

---

pnpm-lock.yaml

resolve #1630 
vuejs/docs@d3169e6 の反映です

chore(deps): bump vue from 3.3.7 to 3.3.8

---

src/translations/index.md

resolve #1655
vuejs/docs@70dfbd1 の反映です

Add Persian to WIP languages

---

package.json
pnpm-lock.yaml
src/examples/ExampleRepl.vue
src/tutorial/TutorialRepl.vue

resolve #1658
vuejs/docs@80bb429 の反映です

chore(deps): bump vue, vitepress, @vue/repl and theme

---

src/guide/introduction.md

resolve #1657 
vuejs/docs@2fbe449 の反映です

docs: updated introduction.md

---

src/guide/essentials/template-refs.md

resolve #1676 
vuejs/docs@1350d08 の反映です

fix: initial value of template refs in Options API

---

.vitepress/theme/components/Home.vue

resolve #1681
vuejs/docs@6f67576 の反映です

style: fix Special Sponsor loading

---

src/guide/quick-start.md

resolve #1683
vuejs/docs@56949a8 の反映です

bump recommended minimum Node.js version

---

package.json
pnpm-lock.yaml

resolve #1700 resolve #1710
vuejs/docs@7d08ac3, vuejs/docs@c15a06f の反映です

use 3.4 beta

---

src/guide/components/provide-inject.md

resolve #1691 
vuejs/docs@51ccfee の反映です

chore: remove outdated warning for reactive provide

---

src/about/coc.md

resolve #1696 
vuejs/docs@f51e4b4 の反映です

sync with contributor-covenant attribution

---

src/guide/best-practices/accessibility.md

resolves #1725
Cherry picked from https://github.com/vuejs/docs/commit/f7555f2fd7000be2d2e9a3677e5f21cbb6867288

fix: Update broken link in accessibility.md (#1725)

---

src/guide/best-practices/accessibility.md

resolve #1699 
vuejs/docs@629dc65 の反映です

docs: replaces 'Not available' with 'search'

---

src/guide/typescript/composition-api.md

resolve #1701
vuejs/docs@4cbc64e の反映です

Update docs on usage of external types in defineProps

---

src/style-guide/rules-strongly-recommended.md

resolve #1707 
vuejs/docs@3a32866 の反映です

fix: remove unnecessary paragraph

---

src/guide/quick-start.md

resolve #1709
vuejs/docs@bcc313c の反映です

feat: add pnpm, yarn and bun support in quick-start

---

package.json
pnpm-lock.yaml

resolve #1735
vuejs/docs@810409f の反映です

bump to 3.4 rc3

---

src/guide/extras/ways-of-using-vue.md

resolve #1734
vuejs/docs@35e1aed の反映です

Update tauri domain

---

src/api/options-misc.md

resolve #1736
vuejs/docs@7e75936 の反映です

fix: delete meaningless paragraphs

---

package.json
pnpm-lock.yaml

resolve #1745
vuejs/docs@37c2fa3 の反映です

deps: use 3.4 proper

---

src/api/built-in-components.md

resolve #1742
vuejs/docs@14d762c の反映です

unify "See also" links

---

src/guide/extras/reactivity-transform.md

resolve #1749 
https://github.com/vuejs/docs/commit/60f19d358f6a4c2ec4979d5132aae6e52a402e94 の内容を反映するものです。

mark reactivity transform removed

---

src/guide/introduction.md

resolve #1771 
vuejs/docs@e19c6be の反映です

update vue 2 mention on intro page

---

src/partners/partners.json

resolves #1775
Cherry picked from https://github.com/vuejs/docs/commit/051d9a85b8814779c0d829dd2d8138bb558eac18

remove partner (#1775)

---

src/api/sfc-script-setup.md
src/error-reference/index.md

resolve #1757
vuejs/docs@89b94d7 の反映です

feat: add defineModel in sfc-script-setup.md

---

src/guide/extras/render-function.md
src/guide/typescript/overview.md

jsxImportSource 

---

src/guide/best-practices/performance.md

resolve #1746 
https://github.com/vuejs/docs/commit/904e85191aa96eae5e1e2db2d50f701ca7289c12 の反映です

remove unnecessary booleans

---

src/api/reactivity-core.md

resolve #1752
https://github.com/vuejs/docs/commit/4b4e0b93cf9dc204f18e750d3afea0306622a17c  の反映です。

「watch() once option」の翻訳

---

pnpm-lock.yaml

resolve #1783 resolve #1788
vuejs/docs@6f19ed7 vuejs/docs@6d91d77 の反映です

chore(deps): bump @vue/repl from 3.1.0 to 3.2.0

---

src/guide/essentials/template-refs.md

resolve #1765
https://github.com/vuejs/docs/commit/7bfcc8a8ae84a501642baff9efb0f392fd87f59f の反映です

Correct template ref grammar

---

src/about/team/members-core.json

resolves #1794
Cherry picked from https://github.com/vuejs/docs/commit/fc57f696e90d8e66f094c04f08548a9677c2affa

Update members-core.json (#1794)

---

pnpm-lock.yaml

resolve #1793 
resolve #1796
resolve #1797
resolve #1800 
resolve #1805

chore(deps): bump vue

---

.vitepress/config.ts
.vitepress/theme/styles/index.css

resolves #1809
Cherry picked from https://github.com/vuejs/docs/commit/95d5e5d21d2743def23ef6cc5a5a045e362bbc4f

chore: move shikiji workaround (#1809)

---

src/translations/index.md

resolve #1806 resolve #1811
vuejs/docs@98628dd, vuejs/docs@c2e0d8e の反映です

feat: Add Czech to WIP languages

---

src/about/team/members-core.json

resolves #1814
Cherry picked from https://github.com/vuejs/docs/commit/4f8a885f9bab59ee872999d159c6af526c60c5bf

fix: change redirection link (#1814)

---

src/guide/extras/ways-of-using-vue.md

resolve #1792
vuejs/docs@8f5dde5 の反映です

docs: recommend tres instead of trois

---

src/tutorial/src/step-1/description.md

resolve #1803 
vuejs/docs@f2f4d13 の反映です

docs: side note about HTML-mode in tutorial

---

src/guide/extras/render-function.md

resolve #1817 
vuejs/docs@a4c52b9 の反映です

fix: add missing anchors on watchers and render-function

---

src/guide/essentials/watchers.md

resolve #1819 resolve #1824
vuejs/docs@80e2128 の反映です

add more details for watcher flush timing

---

src/guide/built-ins/transition-demos/NestedTransitions.vue

resolves #1835
Cherry picked from https://github.com/vuejs/docs/commit/64d58ad9a14b302b292b669a033328e330f68b13

fix: transition nested example (#1835)

---

src/guide/essentials/event-handling.md

resolve #1826 
vuejs/docs@7af1961 の反映です

style: update event-handling.md avoid horizontal scrolling

---

pnpm-lock.yaml

resolve #1816 resolve #1822 
vuejs/docs@cf1b024, vuejs/docs@076aa55 の反映です

chore(deps): bump vue from 3.4.11 to 3.4.15

---

src/guide/components/slots.md

resolve #1834
vuejs/docs@d7a77fe の反映です

Update slots.md link to Dynamic Argument Syntax Constraints

---

src/guide/scaling-up/tooling.md

resolve #1840 
vuejs/docs@1ccf98c の反映です

update `create vue` box

---

src/api/sfc-script-setup.md
src/guide/components/v-model.md

resolve #1841 
vuejs/docs@321453f の反映です

feat: added warnings about v-model

---

src/guide/extras/reactivity-in-depth.md

resolve #1851
vuejs/docs@ab84422 の反映です

docs: update Angular Signals reactivity comparison

---

src/guide/built-ins/transition.md

resolve #1854 
vuejs/docs@6505ade の反映です

docs: add transition + key example

---

src/guide/built-ins/transition.md

resolve #1856 
vuejs/docs@52d8c4b の反映です

docs: add options-api for `Transitions with the Key` example

---

src/api/compile-time-flags.md

resolves #1881
Cherry picked from https://github.com/vuejs/docs/commit/21d4c17faad43a1b294c37063812ab595e66f759

Fix "Hydration" typo (#1881)

---

src/ecosystem/newsletters.md

resolves #1885
Cherry picked from https://github.com/vuejs/docs/commit/90c792983b2c5106ac9216e9a43568cea06e9830

remove inactive newsletter (#1885)

---

.vitepress/config.ts

resolves #1888
Cherry picked from https://github.com/vuejs/docs/commit/31d6411b8b41e9e947ef0c91b477e175ba189b6e

update discord link in nav (#1888)

---

.gitignore
.idea/.gitignore
.idea/aws.xml
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/docs.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #1894
Cherry picked from https://github.com/vuejs/docs/commit/0910c205e60d1d929a910a15f2501a7308f2f818

add vueconf.us banner (#1894)

---

src/ecosystem/themes/themes.json

resolves #1896
Cherry picked from https://github.com/vuejs/docs/commit/6db6990bd7064fc225de87fdbde648fc94d3c0c9

Added Wrappixel Templates (#1896)

---

src/guide/typescript/overview.md

resolve #1871
vuejs/docs@719e350 の反映です

docs: update volar name and remove takeover mode related docs

---

src/guide/extras/ways-of-using-vue.md

resolve #1876
vuejs/docs@58ba3c8 の反映です

docs(extras): move Tauri

---

src/guide/extras/reactivity-in-depth.md

resolve #1878
vuejs/docs@51223f0 の反映です

Fix outdated Immer import in "Immutable Data"

---

src/guide/extras/render-function.md
src/guide/quick-start.md
src/guide/scaling-up/tooling.md

resolve #1883 
vuejs/docs@3149f1a の反映です

docs: update Volar to Vue - Official

---

src/guide/quick-start.md

resolves #1913
Cherry picked from https://github.com/vuejs/docs/commit/162332d46af86296f8601e78b0954b9a652eaf71

docs: fix syntax highlight (#1913)

---

.vitepress/theme/components/NewsLetter.vue
src/about/community-guide.md

resolve #1887 
https://github.com/vuejs/docs/commit/8efb4cf6271fed2cf715416d151183f9241a21e5 の反映です

use direct discord invite link

---

.vitepress/theme/index.ts

resolves #1920
Cherry picked from https://github.com/vuejs/docs/commit/38088c320d1b364d9ce0e9a0e08216c98a721dda

disable vueconf banner temporarily (#1920)

---

.vitepress/theme/index.ts
src/about/team/members-partner.json

resolves #1922
Cherry picked from https://github.com/vuejs/docs/commit/6f9e86709ac80fd19e8c95455fe4a582e7791702

update vincent avatar url (#1922)

---

src/about/team/members-partner.json

resolves #1924
Cherry picked from https://github.com/vuejs/docs/commit/708a6637ba33a8aa461b338a5592dce0aec56547

update jos avatar image (#1924)

---

src/guide/built-ins/suspense.md

resolve #1899
https://github.com/vuejs/docs/commit/c38056cef6cc5ad15d9cfd64c6de2100d18aae78 の反映です

docs: link API reference for Suspense

---

src/guide/best-practices/production-deployment.md
src/guide/extras/composition-api-faq.md

resolve #1907 
https://github.com/vuejs/docs/commit/9173a1d44233c428761a37dad8a62359b92d8f54 の反映です

docs: internal link to compile time flags

---

src/api/composition-api-dependency-injection.md

resolve #1916 
vuejs/docs@6b2e3b3 の反映です

docs: fix 'see also' for provide/inject API page

---

.vitepress/config.ts
src/translations/index.md

resolve #1927 
vuejs/docs@702c75a の反映です

Add translation link to fa.vuejs.org

---

src/guide/essentials/class-and-style.md

resolves #1943
Cherry picked from https://github.com/vuejs/docs/commit/d01c5b3b6e117a68fd2d82fb2689590df272ea0f

Use the correct class variable based on the context (#1943)

---

src/guide/quick-start.md

resolve #1928
https://github.com/vuejs/docs/commit/91339e67a55002dc3b265ce2a8b2a2d88cf05ce1
の対応になります！

update: required node version

---

package.json
pnpm-lock.yaml

resolve #1930 resolve #1933
vuejs/docs@d6252cd, vuejs/docs@f682294 の反映です

bump to vitepress 1.0

---

src/about/team/Member.ts
src/about/team/TeamMember.vue
src/about/team/TeamPage.vue
src/about/team/members-core.json

resolve #1932
vuejs/docs@1731ec5 の反映です

docs: add Kevin Deng as core team member

---

.vitepress/theme/index.ts

resolves #1951
Cherry picked from https://github.com/vuejs/docs/commit/66316a0f97d5068f2d9b50ba8cf3b8240309b7e8

re-enable vueconf us banner (#1951)

---

src/about/community-guide.md

resolve #1934
vuejs/docs@4ffe60b の反映です

fix: link to "Show and tell" forum

---

src/guide/quick-start.md
src/guide/scaling-up/tooling.md
src/guide/typescript/overview.md

resolve #1941
vuejs/docs@ace5d76 の反映です

"VSCode" to "VS Code"

---

src/guide/quick-start.md

resolves #1964
Cherry picked from https://github.com/vuejs/docs/commit/53d29c51c886adf8c70cc0f4f164b09754c12656

chore: update create-vue output (#1964)

---

.vitepress/config.ts
src/translations/index.md

resolve #1950 
vuejs/docs@e77511d の反映です

feat: czech translation

---

.vitepress/config.ts
src/translations/index.md

resolve #1953 resolve #1955
vuejs/docs@d77e5a1 vuejs/docs@88a601b の反映です

Add translation link to ru.vuejs.org

---

src/api/sfc-css-features.md

resolve #1957 
vuejs/docs@306ead6 の反映です

docs: modify link

---

src/guide/components/slots.md

resolve #1963 resolve #1967
vuejs/docs@1ab62a5, vuejs/docs@e7163d4

docs: added conditional slots section in slots guide

---

.vitepress/config.ts

resolves #1981
Cherry picked from https://github.com/vuejs/docs/commit/6e1c211f3a0a40314ccfc73f95f683cb885f029f

chore: update algolia api key (#1981)

---

package.json
pnpm-lock.yaml

resolve #1974
resolve #1976
vuejs/docs@480e12d, vuejs/docs@a177175 の反映です

chore: bump vitepress

---

src/api/built-in-components.md
src/guide/built-ins/suspense.md

resolve #1978 resolve #1980
vuejs/docs@c1de1dd, vuejs/docs@3d854a0 の反映です

feat(Suspense): add suspensible prop information

---

src/guide/built-ins/transition.md

トランジションのページでタイポ見つけたので修正しました (DON -> DOM)。

fix typo (DON -> DOM)

---

pnpm-lock.yaml

chore(deps): bump vue from 3.4.21 to 3.4.23

---

src/guide/quick-start.md

resolves #2013
Cherry picked from https://github.com/vuejs/docs/commit/c42ab53cb40f430340c393cedd8d345da0081697

fix: update create-vue option info (#2013)

---

src/guide/components/v-model.md

resolves #2015
Cherry picked from https://github.com/vuejs/docs/commit/21cd803662e9ed58ca0253cd21ebba2acad82ae9

docs: format code block comments (#2015)

---

LICENSE

resolves #2020
Cherry picked from https://github.com/vuejs/docs/commit/8cf681562260f8624ef062512485fbc86870dec5

update license to CC-BY-4.0 and explicitly exclude images (#2020)

---

pnpm-lock.yaml

resolve #2000
vuejs/docs@5451f5b の反映です

chore(deps): bump vue from 3.4.23 to 3.4.25

---

src/tutorial/src/step-11/App/composition.js

resolves #2031
Cherry picked from https://github.com/vuejs/docs/commit/980866bd3a2832eb0fdc08fa8cbb8b02470a2fd5

docs: ensure consistency in comment in guide step-11 (#2031)

---

.vitepress/config.ts
.vitepress/inlined-scripts/uwu.js
.vitepress/theme/components/Home.vue

resolves #2043
Cherry picked from https://github.com/vuejs/docs/commit/569925760954602919b89ef1a6bcb60ebf3e92e7

avoid uwu logo layout shift (#2043)

---

src/api/reactivity-utilities.md

resolves #2049
Cherry picked from https://github.com/vuejs/docs/commit/b786ffd8cb02ade7d40622e292fb13c0f5c133cd

feat: update isProxy() param type (#2049)

---

.vitepress/theme/components/Home.vue

resolve #2052 
vuejs/docs@12a2591 の反映です

Fix: uwu logo style & alt text from Home.vue

---

src/guide/extras/reactivity-in-depth.md

resolve #2030
vuejs/docs@c70fdb3 の反映です

docs: add vue vapor repo link

---

.vitepress/config.ts

resolve #2041
vuejs/docs@4c1e2c1 の反映です

docs: update link to official certification website

---

src/api/built-in-directives.md
src/examples/src/list-transition/App/template.html
src/examples/src/modal/App/template.html
src/examples/src/todomvc/App/template.html
src/guide/built-ins/keep-alive-demos/CompA.vue
src/guide/components/attrs.md
src/guide/components/events.md
src/guide/components/v-model.md
src/guide/essentials/watchers.md
src/guide/extras/reactivity-in-depth.md
src/guide/extras/render-function.md
src/guide/quick-start.md
src/tutorial/src/step-2/description.md
src/tutorial/src/step-4/App/template.html
src/tutorial/src/step-4/_hint/App/template.html
src/tutorial/src/step-6/App/template.html
src/tutorial/src/step-6/_hint/App/template.html
src/tutorial/src/step-9/App/template.html

resolve #2042
vuejs/docs@7ae6897 の反映です

docs: fix writing mistakes in letter case

---

pnpm-lock.yaml

resolve #2036
vuejs/docs@d4b8dec の反映です

chore(deps): bump vue from 3.4.25 to 3.4.26

---

src/guide/components/v-model.md

resolve #2045
vuejs/docs@288f7bf の反映です

docs: add docs for v-model `update:*` event

---

src/guide/best-practices/accessibility.md

resolve #2046
vuejs/docs@c86beff の反映です

refactor: remove unuseful comments

---

.vitepress/headerMdPlugin.ts

resolves #2075
Cherry picked from https://github.com/vuejs/docs/commit/35e8da8b3811615e3a46770cf4466186ac9ff400

fix: broken header plugin (#2075)

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

Vue Fes Japan 2024 スポンサー2次募集広告

---

pnpm-lock.yaml

resolve #2092
vuejs/docs@9329dbc の反映です

chore(deps): bump vue from 3.4.26 to 3.4.27

---

src/guide/scaling-up/testing.md

resolve #2087 resolve #2094
vuejs/docs@6bd7cc7, vuejs/docs@809e830 の反映です

docs: Correct browser support sentences for Playwright and Cypress

---

README.md

resolve #2101 
vuejs/docs@804620d の反映です

chore: update node version in readme

---

.npmrc

resolves #2113
Cherry picked from https://github.com/vuejs/docs/commit/e276daba15586ca2f993661cc0d7fe9ce84954d7

chore: add .npmrc (#2113)

---

.vitepress/config.ts
src/translations/index.md

resolve #2109
vuejs/docs@11a07af の反映です

docs: add zh-hk to language list

---

package.json
pnpm-lock.yaml

resolve #2112
vuejs/docs@f3f878c の反映です

chore: update theme

---

.github/workflows/ja.yaml

- GitHub Actions のアクションを v3 → v4 に更新
- pnpm のアクションに移行

GitHub Actions のアクションのバージョン更新

---

.vitepress/config.ts
package.json
pnpm-lock.yaml

resolve #2123 
vuejs/docs@ff4e7c7 の反映です

chore: bump deps

---

src/guide/extras/composition-api-faq.md

resolve #2126 
vuejs/docs@40e2617 の反映です

add a note about react compiler

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

Vue Fes Japan 2024 CFP開始広告

---

.gitignore
src/guide/essentials/reactivity-fundamentals.md

未翻訳コメントの対応

---

src/guide/essentials/reactivity-fundamentals.md

fix (「独自」 -> 「元のオブジェクト」)

---

src/guide/extras/rendering-mechanism.md

resolves #2146
Cherry picked from https://github.com/vuejs/docs/commit/a7d0726f7180c6a474bc13050d0ced8fd9cd68b0

fix: update example in guide/extras/rendering-mechanism (#2146)

---

pnpm-lock.yaml

resolve #2154
vuejs/docs@c0724f7 の反映です

chore(deps): bump vue from 3.4.27 to 3.4.29

---

src/guide/components/v-model.md

resolve #2155
vuejs/docs@cba9103 の反映です

doc: update v-model.md

---

src/api/render-function.md

resolves #2162
Cherry picked from https://github.com/vuejs/docs/commit/9eaf513ea69b69280a83fd0bc608b80dc4f198ec

docs(withModifiers): change type of withModifiers param (#2162)

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/SecurityUpdateBtn.vue
.vitepress/theme/index.ts

resolve #2161 
vuejs/docs@8a4f627 の反映です

chore: add redirect to herodevs site for vue 2

---

.vitepress/theme/components/SecurityUpdateBtn.vue

resolve #2167
vuejs/docs@5a02126 の反映です

fix: scope SecurityUpdateBtn css styles

---

pnpm-lock.yaml

resolve #2177
vuejs/docs@7ae2dac の反映です

chore(deps): bump vue from 3.4.31 to 3.4.32

---

src/about/team/members-partner.json

resolve #2180 
vuejs/docs@4733055 の反映です

chore: update team member

---

pnpm-lock.yaml

resolve #2190 
vuejs/docs@a2fbd35 の反映です

chore(deps): bump vue from 3.4.32 to 3.4.33

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

Vue Fes Japan 2024 チケット広告

---

src/api/sfc-script-setup.md

resolve #2191 
vuejs/docs@0408888 の反映です

Add note about how to reference generic components

---

pnpm-lock.yaml

resolve #2205 
vuejs/docs@78c7138 の反映です

chore(deps): bump vue from 3.4.33 to 3.4.35

---

.vitepress/theme/components/Home.vue

resolve #2204 
vuejs/docs@6f60bf1 の反映です

chore: remove trailing spaces in home

---

.vitepress/config.ts
package.json

resolve #2203 
vuejs/docs@433d4be の反映です

feat: generate sitemap

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

Vue Fes Japan 2024 チケット広告修正

---

src/guide/typescript/composition-api.md

resolve #2220
vuejs/docs@8a1da00 の反映です

Add docs on how to reference generic components

---

src/guide/components/v-model.md

resolve #2218
vuejs/docs@308f479 の反映です

docs: remove unnecessary props using

---

.vitepress/theme/styles/style-guide.css

resolve #2215 
vuejs/docs@a66c916 の反映です

fix: summary add cursor pointer

---

src/guide/quick-start.md
src/guide/scaling-up/tooling.md

resolve #2212
vuejs/docs@4de8ccb の反映です

Update yarn create command

---

.vitepress/config.ts
package.json
pnpm-lock.yaml

resolve #2228
vuejs/docs@3d56a01 の反映です

chore: bump vue, vitepress & use built-in minify

---

src/about/team/members-emeriti.json

resolves #2237
Cherry picked from https://github.com/vuejs/docs/commit/44fc18fcf00851f7c2f0b91f544db79784cf4d7c

docs: update defcc latest information (#2237)

---

src/api/options-misc.md

resolve #2236 
https://github.com/vuejs/docs/commit/9a4c8127181cc411e1a330d692b6d7c457f06db1 の反映です。
ご確認のほどよろしくお願いいたします。

Added a link explaining how to use inheritAttrs in normal <script> (#2971)

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

Vue Fes Japan 2024 チケット広告 早割延長

---

src/about/team/members-core.json

resolves #2242
Cherry picked from https://github.com/vuejs/docs/commit/059bdf25f42d3ab3368c3a2e43cc8b503af8ddaa

Update Yiling's personal information (#2242)

---

package.json
pnpm-lock.yaml

resolve #2248
vuejs/docs@2584dd1 の反映です

bump vue to 3.5

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

Vue Fes Japan 2024 チケット広告更新（早割終了）

---

package.json
pnpm-lock.yaml

resolve #2287, resolve #2293, resolve #2294
vuejs/docs@eb0871f, vuejs/docs@cf2bcd1, vuejs/docs@558d2e7 の反映です

upgrade pnpm

---

src/guide/extras/render-function.md

resolve #2296
https://github.com/vuejs/docs/commit/1fb260a42f0028c9d87021255bce2b7fc640f500 の反映です

fix: createVnode() -> createVNode()

---

src/guide/quick-start.md

resolve #2297
vuejs/docs@481de31 の反映です

docs: update quick start instructions for yarn v1

---

src/guide/best-practices/accessibility.md

resolve #2306 
vuejs/docs@b3b1b89 の反映です

docs: update a11y docs for landmarks

---

src/developers/developers.json

resolves #2337
Cherry picked from https://github.com/vuejs/docs/commit/b15177c4bcfe7e37958ff3a19a13dd9d8756cd18

docs(developers): remove duplicate text (#2337)

---

src/guide/reusability/plugins.md

resolve #2322
https://github.com/vuejs/docs/commit/fd16694c3d2978312951f8aaae1e1e3d155c348c の反映対応です

docs: Update plugins.md on how to bundle a plugin.

---

src/guide/scaling-up/testing.md

resolve #2333
vuejs/docs@9ff4a35 の反映です

docs: fix broken link to Playwright Component Testing

---

src/api/reactivity-core.md

resolve #2335
vuejs/docs@cfcf01e の反映です

docs(api): format WatchSource type

---

src/api/built-in-special-attributes.md

resolve #2359
vuejs/docs@a681541 の反映です

docs: update ref attribute example

---

src/guide/essentials/event-handling.md

resolve #2358
vuejs/docs@756b51d の反映です

Update KeyboardEvent.key MDN URL

---

src/guide/essentials/template-refs.md

resolve #2357
vuejs/docs@08feb34 の反映です

docs: fix required version for useTemplateRef

---

src/guide/essentials/template-refs.md

resolve #2355
vuejs/docs@96b9b7c の反映です

docs: improve clarity on using refs

---

src/tutorial/tutorial.data.ts

resolves #2380
Cherry picked from https://github.com/vuejs/docs/commit/cf84ce10597785e6dfa2f2fb6db5d6a0b4810b32

fix: Tutorial Syntax Highlight (#2380)

---

src/api/sfc-css-features.md

resolve #2377 
https://github.com/vuejs/docs/commit/b66b1d2fbf2cad70f98a7cba9e941d3c99bf80eb の反映です。
ご確認のほどよろしくお願いいたします。

add useCssModule example (#3070)

---

src/about/team/members-core.json

resolves #2383
Cherry picked from https://github.com/vuejs/docs/commit/929aff014b0595dda64f31361e8b37b5d6eb750c

Update Natalia's role (#2383)

---

src/guide/built-ins/transition-group.md

resolve #2379
vuejs/docs@e419207 の反映です

Update transition-group.md - add detail about prop moveClass

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue

resolve #2392
vuejs/docs@58c4b89 の反映です

Add VueToronto banner to the docs

---

src/about/team/members-core.json
src/about/team/members-emeriti.json

resolves #2395
Cherry picked from https://github.com/vuejs/docs/commit/f7a80d4eac57d45f170cd8ae50e88613b703017f

move hcy and rahul to team emiriti (#2395)

---

src/public/funding.json

resolves #2398
Cherry picked from https://github.com/vuejs/docs/commit/dcf9415318cb6c4105b51dd83852304988f065c2

add funding.json (#2398)

---

src/guide/built-ins/transition-group.md

resolve #2404
vuejs/docs@b266b81 の反映です

Update the transition group

---

src/examples/src/fetching-data/App/composition.js
src/examples/src/fetching-data/App/options.js
src/examples/src/fetching-data/App/template.html
src/examples/src/fetching-data/description.txt

resolves #2406
Cherry picked from https://github.com/vuejs/docs/commit/ce19be89b28ce7ebc9aa257663c37b847466fc66

fix(example): fix repo and branches names in fetching example (#2406)

---

pnpm-lock.yaml

resolve #2408
vuejs/docs@b1b5555 の反映です

chore(deps): bump vue from 3.5.12 to 3.5.13

---

src/guide/extras/reactivity-in-depth.md

resolve #2427
vuejs/docs@ac1682b の反映です

docs: update angular signals link

---

.vitepress/theme/components/SponsorsGroup.vue

resolves #2435
Cherry picked from https://github.com/vuejs/docs/commit/d0a13f7c2d345c9c50bb8bd113e7f7c1105bf9b1

update special sponsorship link in sidebar (#2435)

---

src/guide/components/slots.md

resolve #2444 
https://github.com/vuejs/docs/commit/c1af45940e6c73efb9ee4dcffc6ce4437ff2e31e の反映です

docs(guide/components/slots): clarify slot presence phrasing

---

src/api/application.md

resolve #2462
vuejs/docs@b5ff5db の反映です

use PascalCase

---

src/guide/extras/render-function.md

resolve #2475 
https://github.com/vuejs/docs/commit/185a5f335cded671de842ce28f5f128c614ce275 の反映です

docs: update template refs render function

---

src/api/component-instance.md

resolve #2473
https://github.com/vuejs/docs/commit/d6b50e88d0f48aff49a4f7074b6f71e6e088dd3f の反映です

docs: fix $el type in documentation to 'any'

---

src/api/custom-renderer.md

resolve #2468
https://github.com/vuejs/docs/commit/a06db6c023a33d8073c6fa1f6e5d4827e4c5e58e の反映です

Update RendererOptions  according to the latest source code

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #2484
Cherry picked from https://github.com/vuejs/docs/commit/3735fb4ffd02c28add7a9a44c51636b8d5fa0455

feat(*): add madvue banner (#2484)

---

src/translations/index.md

resolve #2493 
https://github.com/vuejs/docs/commit/9f3814a10dab0c11da43872926d3c1b5a755af5a の反映です

Add German language links to the translations page

---

src/translations/index.md

resolve #2496 
https://github.com/vuejs/docs/commit/dfe4c91a2bbdd1638540fb840ab11a5b0961cf0a の反映です

Update German website URL

---

.vitepress/config.ts
.vitepress/theme/components/Home.vue
.vitepress/theme/components/SponsorsGroup.vue
.vitepress/theme/components/sponsors.ts

resolve #2504
https://github.com/vuejs/docs/commit/6f14d3e0ab79909523d211d0b7b0fe5329b2fbbf の反映です

theme: workaround adblock for sponsors

---

src/guide/components/provide-inject.md

resolve #2508
https://github.com/vuejs/docs/commit/7cabdc93564a12e3b224cae47bdf3c636c0cc35e の反映です

docs: Clarify inject data when multiple parent provide the same key

---

src/partners/partners.json

resolves #2518
Cherry picked from https://github.com/vuejs/docs/commit/f3e9cfb41c21e3c78d1a6ef2a7da2b187b79b755

update monterail url (#2518)

---

.vitepress/config.ts
.vitepress/inlined-scripts/uwu.js
.vitepress/theme/components/Home.vue

resolve #2065
https://github.com/vuejs/docs/commit/a95e91000f166d5e2e63d6692411546982bd440e の一部を反映

bring back the uwu logo

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolves #2527
Cherry picked from https://github.com/vuejs/docs/commit/c707b2b850e91dd8b551172af08dc32e23c284fb

added banner for vueconf 2025 (#2527)

---

src/guide/built-ins/transition.md

resolves #2530
Cherry picked from https://github.com/vuejs/docs/commit/2e07b40b2b55dfaa629143e9ffc56404027342ca

docs: fix blockquote language (#2530)

---

src/guide/essentials/computed.md

resolve #2532 
https://github.com/vuejs/docs/commit/0cafdc5176731e4e933b4a3696b415b42aeb01d2 の反映です

docs(computed): correct parameter in computed example

---

.vitepress/config.ts
src/translations/index.md

resolve #2538 
https://github.com/vuejs/docs/commit/c9186a6f0c029ac6a5edaf6216ca08ac5a069be7 の反映です

feat: Mark Polish translation as complete

---

src/api/sfc-script-setup.md

resolve #2552 
https://github.com/vuejs/docs/commit/2859a4562f7f01323110202c3bc9e68ea2f914e7 の反映です

docs: include example of `@vue-generic` directive

---

src/api/sfc-script-setup.md

resolves #2560
Cherry picked from https://github.com/vuejs/docs/commit/7adfb64cf35de348a4c86a6eaf0f95053fa63838

fix: shorten variable names to avoid code block overflow (#2560)

---

src/guide/extras/ways-of-using-vue.md

resolve #2562
https://github.com/vuejs/docs/commit/5a1e8c27b355548329a17e0d8c306b1736607ad9 の反映です

chore: add wails as an alternative desktop framework

---

.vitepress/config.ts
package.json
pnpm-lock.yaml
src/public/_redirects

Revert "feat(docs): add a plugin to generate documentation for LLMs (#2558)

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

resolve #2580
https://github.com/vuejs/docs/commit/fcee6236c1e2c3ecf0cc85945eb1db120f43af10 の反映です

vueconf us banner offline

---

src/guide/extras/animation.md

resolve #2584
https://github.com/vuejs/docs/commit/c80de28a4af9030e4d0342bb68a33c18fc16b907 の反映です

docs(animation): add MAX_SAFE_INTEGER warning for large input edge case

---

src/guide/essentials/forms.md

resolve #2616 
https://github.com/vuejs/docs/commit/21003878f0678162a4e328be9839915cd780a49d の反映です

docs: add demo for dynamic select options in form essentials

---

src/about/privacy.md

resolve #2617
https://github.com/vuejs/docs/commit/b67757e2d56f900d807672441a04ad91083d3939 の反映です

docs: fix a typo in the Privacy Policy

---

.vitepress/config.ts

resolve #2641
https://github.com/vuejs/docs/commit/4e8c0623d6ab692eb58a293300fc61f06e79b77a の反映です

feat: add Vue Plugins to the resources list

---

.vitepress/config.ts

resolve #2666
https://github.com/vuejs/docs/commit/31b4521ad0607a74e284fa7c62502b56a7710e86 の反映です

fix(nav): update Twitter link to x.com
