- src/api/sfc-css-features.md
resolves #57
Cherry picked from https://github.com/vuejs/docs/commit/c78a8601918076526a9ed99b8ba813df61a0cfa3
> docs: fix typo (#57)

- src/guide/built-ins/transition.md
- src/guide/essentials/reactivity-fundamentals.md
resolves #138
Cherry picked from https://github.com/vuejs/docs/commit/00d2dc42238d1cb6c5393ca18c0d9243cc626283
> chore: fix typo in code example (#138)

- package.json
package.json で Node バージョンと packageManager を指定
- フィールドの値を書き換えると `pnpm -v` の結果が変わることを確認
- pnpm は現時点の最新バージョンを指定
> package.json で Node バージョンと packageManager を指定

- .textlintrc
- pnpm-lock.yaml
`textlint-rule-preset-vuejs-jp` を最新にして、`.textlintrc` にルール追加しました。
> add textlint "カタカナの長音" rule

- src/api/options-rendering.md
resolves #274
Cherry picked from https://github.com/vuejs/docs/commit/4fb2d4cb9f5c47e5b93166f1254bb90829c92550
> Update the API entry for the template option (#274)

- .github/CONTRIBUTING.md
CONTRIBUTING のページに、[用字、用語](https://github.com/vuejs-translations/docs-ja/wiki/%E7%94%A8%E5%AD%97%E3%80%81%E7%94%A8%E8%AA%9E) のルールに従っていない翻訳例があったので修正しました。
> 用字、用語ページのルールに従って修正

- src/guide/essentials/lifecycle.md
resolve #16
---
* コードブロック内の英語について、[翻訳ガイド](https://github.com/vuejs-translations/docs-ja/blob/main/.github/CONTRIBUTING.md) に指定が見つからなかったので翻訳対象にしていますが、もし見落としていた場合はご指摘いただければと思います。
> 「Guide > Essentials > Lifecycle Hooks」の翻訳

- .vitepress/config.ts
- src/guide/typescript/overview.md
resolve #45  
[src/guide/typescript/overview.md](https://github.com/vuejs-translations/docs-ja/blob/main/src/guide/typescript/overview.md) の翻訳をしました。  
Vue 3 旧ドキュメントの翻訳を一部参考にさせていただきました。  
ドキュメントの翻訳は初めてなのでおかしい点などがあるかもしれませんが、よろしくお願いします。
> 「Guide > TypeScript > Overview」の翻訳

- src/api/sfc-spec.md
resolves #365
Cherry picked from https://github.com/vuejs/docs/commit/8efc2116a2f94634c4d88561f9ab027d8530fe9f
> fix: correct Markdown syntax and broken links (#365)

- src/api/application.md
resolves #456
Cherry picked from https://github.com/vuejs/docs/commit/aac00ea380168e2a8a77b421a6601788ff063085
> docs: refine the `application` documentation link (#456)

- src/api/general.md
- src/guide/typescript/overview.md
resolve #603
vuejs/docs@b4112ff の取り込みです
`src/api/general.md` は全体的に未翻訳のため、そのまま反映
> add a note on defineComponent() treeshaking with webpack

- src/guide/best-practices/accessibility.md
resolve #621
vuejs/docs@d602af1 の反映です
#653 を先に取り込んだため、途中から元の差分と行番号がずれています
> fix: fix links for aria-attributes

- src/tutorial/src/step-2/description.md
resolve #654
vuejs/docs@4e50369 では SFC のハイフンを修正していますが、日本語に変更しました
（他にも英語のままになっている箇所があるので issue 建てておきます）
> Fix typo - hyphenate Single-File Component

- src/guide/essentials/watchers.md
resolve #690
本家の vuejs/docs@4eb8569 では `the` を追加する修正なので直接関係ないのですが、該当箇所が `Option API` になっているのに気づいたので修正しました
> Fixed a grammar mistake

- .vitepress/config.ts
resolve #919
`@vue/theme` アップデートの際、プロパティ名を修正する旨のコメントを追加しました
> config にコメント

- src/guide/components/async.md
resolve #992
vuejs/docs@39e9e0e の反映です
MDN 日本語版のページがまだないので、英語版の URL にしてあります
> update to a correct link for dynamic imports

- src/api/sfc-script-setup.md
resolve #1062 
vuejs/docs@95aabcf の反映です
> Add caveats around mixing `<script setup>` and `<script>`

- src/api/built-in-special-elements.md
- src/api/reactivity-core.md
- src/guide/best-practices/accessibility.md
- src/guide/essentials/event-handling.md
- src/guide/essentials/forms.md
- src/guide/essentials/reactivity-fundamentals.md
- src/guide/essentials/template-syntax.md
- src/guide/scaling-up/ssr.md
resolve #1026
英語版のリンクのままになっている箇所を `en-US` → `ja` に差し替え。
日本語版のページがない場合は TODO コメントを追加
> MDN のリンクを日本語版のページに

- src/guide/extras/ways-of-using-vue.md
resolve #1184
vuejs/docs@0631aa5 の反映です
> docs(guide-extra): change terminal to `vue-termui` link

- vercel.json
When no extension is used, page is broken with redirection: https://ja.vuejs.org/guide/introduction
Suggested by Evan You in private: vuejs.org uses Netlify with `cleanUrls` enabled.
Enabling it is solving the issue.
> fix: enable Vercel's cleanUrls options to avoid redirection issue

- src/guide/components/events.md
https://ja.vuejs.org/guide/components/events.html#declaring-emitted-events においてインデントが適切でない箇所があったため、修正しました。
> Fix indentation in events.md

- src/api/sfc-script-setup.md
resolve #1343
vuejs/docs@9146302 の反映です
> move type-based usage of defineProps & defineEmits to the same section

- .vitepress/theme/components/PreferenceTooltip.vue
API スタイル切替の tooltip が英語のままだったので翻訳
> API スタイル切替の tooltip を翻訳

- src/guide/typescript/overview.md
https://github.com/vuejs/docs/commit/ead4aa2 の反映漏れ対応
> update references to volar

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
> Vue Fes Japan 2023 チケット広告（早割延長）

- src/guide/best-practices/accessibility.md
resolves #1600
Cherry picked from https://github.com/vuejs/docs/commit/009cb997ae021070d23f8520633ba24f5209e746
> docs: remove broken link to focus indicator extension (closes #2530) (#1600)

- src/guide/scaling-up/testing.md
resolve #1620
vuejs/docs@9e0d774 の反映です
> docs: use useByRole in example and fix typos

- .vitepress/theme/styles/index.css
resolves #1661
Cherry picked from https://github.com/vuejs/docs/commit/b2bca5567e0e65ed7b5e365427fafa9e5a4e416d
> fix syntax highlight for vitepress rc.31 shijiki migration (#1661)

- src/api/composition-api-dependency-injection.md
resolve #1665 
vuejs/docs@0517a16 の反映です
> feat: add hasInjectionContext API

- src/guide/components/events.md
- src/guide/typescript/composition-api.md
resolve #1667 resolve #1702
vuejs/docs@48ea900, vuejs/docs@c394c62 の反映です
> docs: added events as props and typing with object based emits

- src/guide/quick-start.md
resolve #1857 
vuejs/docs@b48716c の反映です
> docs: recommend `petite-vue` for no build approaches

- src/guide/reusability/custom-directives.md
resolve #1910
https://github.com/vuejs/docs/commit/a8cf7bf44ada19452c765a1958753adf0d398e99
の修正になります。
ご確認お願いします 🙏
> docs: fix typo - prevNode should be prevVnode

- src/guide/components/props.md
resolve #2001 
https://github.com/vuejs/docs/commit/26666c032a07fc66531f063ca52646e99cdb6cde の反映です。
ご確認のほどよろしくお願いいたします。
> document nullable types

- pnpm-lock.yaml
resolve #1990
vuejs/docs@0beaed8 の反映です
> chore(deps): bump vitepress from 1.1.0 to 1.1.3

- src/api/sfc-script-setup.md
resolve #2012
https://github.com/vuejs/docs/commit/15ada9d4b8ee42d7c341a3ec819abee0df5877bf
の対応になります
> docs: link to suspense

- src/guide/built-ins/keep-alive.md
> docs: fix a typo

- pnpm-lock.yaml
resolve #2035 
vuejs/docs@baf27c8 の反映です
> chore(deps): bump vitepress from 1.1.3 to 1.1.4

- src/api/reactivity-core.md
resolve #2073
vuejs/docs@1f95b22 の反映です
> fix: link to getter function definition

- src/api/sfc-spec.md
resolves #2105
Cherry picked from https://github.com/vuejs/docs/commit/7493b263972c078e39db3b3e4b41ac3e01f5f539
> fix: correctly link to i18n custom blocks (#2105)

- pnpm-lock.yaml
resolve #2164 resolve #2168
vuejs/docs@a54f297, vuejs/docs@99de305 の反映です
> chore(deps): bump vitepress from 1.2.3 to 1.3.0

- pnpm-lock.yaml
resolve #2182
vuejs/docs@618f500 の反映です
> chore(deps): bump vitepress from 1.3.0 to 1.3.1

- pnpm-lock.yaml
resolve #2214
vuejs/docs@1113c8a の反映です
> chore(deps): bump vitepress from 1.3.1 to 1.3.2

- package.json
- pnpm-lock.yaml
resolve #2241, resolve #2246
vuejs/docs@c38ade5, vuejs/docs@c69984f の反映です
> chore(deps): bump vitepress from 1.3.2 to 1.3.4

- src/style-guide/rules-essential.md
resolve #2245 
https://github.com/vuejs/docs/commit/253615a516cb61efecfd4d134dc4ef2bc5706586 の反映対応です
> docs: update scoped CSS links in style guide

- src/api/reactivity-core.md
- src/guide/essentials/watchers.md
resolve #2263 
https://github.com/vuejs/docs/commit/66a8ced546bc2feb3b9bb90c09b236039f621b65 の反映です。
> docs: Update watcher side effect cleanup + WatchHandle pause / resume

- src/api/composition-api-helpers.md
resolves #2300
Cherry picked from https://github.com/vuejs/docs/commit/e20eb77a4ef3e0c32c081be7190cb861400c37ff
> docs: missed return value type for useModel() (#2300)

- src/api/sfc-script-setup.md
This pull request will update the heading level in the “Generics” section of the `sfc-script-setup.md` file. The heading level has been changed from `###` to `##` for consistency with the original documentation.
Original: https://github.com/vuejs/docs/blob/main/src/api/sfc-script-setup.md#generics--generics
> docs: update heading level for Generics section

- src/api/reactivity-core.md
resolve #2299
vuejs/docs@27dd985 の反映です
> docs: fixes in 3.5 updates on reactivity-api page

- src/guide/scaling-up/testing.md
resolve #2302
vuejs/docs@f3b6dcf の反映です
> docs: move Playwright to recommended frameworks

- src/guide/components/async.md
- src/guide/components/props.md
> docs: add omitted anchors for 3.5

- src/guide/built-ins/suspense.md
resolve #2318
vuejs/docs@e61a1c0 の反映です
> fix(guide/suspense): missing v3.3+ badge in suspensible prop

- pnpm-lock.yaml
resolve #2319
vuejs/docs@808ad46 の反映です
> chore(deps): bump vue from 3.5.5 to 3.5.8

- pnpm-lock.yaml
resolve #2332
vuejs/docs@b1a6899 の反映です
> chore(deps): bump vue from 3.5.8 to 3.5.9

- src/guide/reusability/custom-directives.md
resolve #2305・#2325
- https://github.com/vuejs/docs/commit/ac7a921f0124c62b993fa2059e7a21db6877f9de
- https://github.com/vuejs/docs/commit/15bae507bfb2856a2f2a2dbde7be1baa61d1ec49
の反映対応です
> docs: fix issue with autofocus on custom directives page

- pnpm-lock.yaml
resolve #2339
vuejs/docs@e45d0e2 の反映です
> chore(deps): bump vue from 3.5.9 to 3.5.10

- src/guide/essentials/computed.md
resolve #2331 
vuejs/docs@4567e55 の反映です
> feat(guide/computed): add previous to computed

- src/guide/typescript/options-api.md
- src/guide/typescript/overview.md
resolve #2324 
https://github.com/vuejs/docs/commit/2ec007be666b0826926a2564ecd3e42d08ce226e の反映対応です
> docs: fix broken links to dts-test files

- src/guide/essentials/computed.md
Writable Computedの説明でsetter関数の呼び出し方を修正しました。
英語版は、 `fullName.value = 'John Doe'` になっていました。
> docs: fix the description of Writable Computed in Composition API

- src/guide/essentials/template-refs.md
resolve #2365
vuejs/docs@017ce15 の反映です
> docs(essentials/template-refs): fix typo

- pnpm-lock.yaml
resolve #2364
vuejs/docs@a9c6189 の反映です
> chore(deps): bump vitepress from 1.4.0 to 1.4.1

- .vitepress/theme/components/Home.vue
- .vitepress/theme/components/SponsorsGroup.vue
- src/sponsor/index.md
resolve #2385 resolve #2388
vuejs/docs@6dd2f7a, vuejs/docs@18eaa5e の反映です
> special sponsor vacancy handling

- src/tutorial/src/step-9/description.md
- 軽微な文章の修正を行いました
- `<p>` の要素にアクセスして xxxx がより自然なので修正
> docs: Fix typo in step-9 description.md

- .vitepress/theme/components/PageHero.vue
- src/developers/components/DeveloperHero.vue
- src/developers/partnerConfig.js
- src/partners/components/PartnerHero.vue
resolve #2394 
vuejs/docs@597abd1 の反映です
> Improvements to partnership page

- src/guide/extras/web-components.md
resolve #2402
vuejs/docs@1cea431 の反映です
> Corrected and improved docs on type definitions for Custom Elements.

- src/guide/typescript/composition-api.md
resolves #2422
Cherry picked from https://github.com/vuejs/docs/commit/129c27cfc7fcb056a2e2ae4e092e99712eb84045
> docs: correct usage examples of `useTemplateRef` (#2422)

- src/guide/essentials/computed.md
- src/guide/typescript/composition-api.md
resolves #2428
Cherry picked from https://github.com/vuejs/docs/commit/5936eef341f8c0c62b36d80ad2007b36c10602ee
> docs(computed): remove semicolons (#2428)

- src/guide/extras/web-components.md
resolve #2430
vuejs/docs@8ce9c23 の反映です
> docs: add missing anchor

- src/guide/extras/web-components.md
resolve #2426
vuejs/docs@d600fe1 の反映です
> docs: update link to volar wiki

- src/guide/components/v-model.md
resolve #2424
vuejs/docs@524de31 の反映です
> docs: make `v-model` code example more readable

- src/guide/essentials/template-refs.md
resolve #2447
https://github.com/vuejs/docs/commit/dd5e8c8f0807538dc7e62e5f93cc5646480cb86e の反映です
> docs: add explanation for template-refs defineExpose before await

- .vitepress/config.ts
resolve #2445
https://github.com/vuejs/docs/commit/7d15b57975031eaa1c4b0de2398bbabb31327742 の反映です
> docs: changed lifecycle hooks to be after components basics in sidebar

- src/guide/extras/web-components.md
resolve #2452
https://github.com/vuejs/docs/commit/a10d1cc3da8197c35d64f7f087563c3153703272 の反映です
> fix: formatting in new web-components content

- src/guide/essentials/component-basics.md
resolve #2471
https://github.com/vuejs/docs/commit/27b5615160b47e1ff5c71ff621db0b2ff34a5462 の反映です
> Update component-basics.md - wrong highlight about slot

- pnpm-lock.yaml
resolve #2465
https://github.com/vuejs/docs/commit/a8c26ae30fc1715157927ba3cd0cc0cb8e3006a6 の反映です
> chore(deps): bump vitepress from 1.5.0 to 1.6.0

- pnpm-lock.yaml
resolve #2492
https://github.com/vuejs/docs/commit/3f4d2237fb8f623711cb1e82dc8d2dd95e0e6432 の反映です
> chore(deps): bump vitepress from 1.6.0 to 1.6.3

- src/api/sfc-script-setup.md
`defineOptions()` の見出しから  ` />` を削除しました。
[該当のページ](https://ja.vuejs.org/api/sfc-script-setup#defineoptions)
ご確認の程よろしくお願いします。
> docs: fix typo

- src/guide/best-practices/accessibility.md
resolve #2501 
https://github.com/vuejs/docs/commit/7119fae1205bc9adf5b229be3c8d56acac027a77 の反映です
> Change the way focus is set in skip link example code

- netlify.toml
resolves #2511
Cherry picked from https://github.com/vuejs/docs/commit/899ec065e760e1f6e85fd545a41d01d59e3f2eb8
> chore: bump node version on netlify (#2511)

- src/guide/scaling-up/tooling.md
resolve #2537 
https://github.com/vuejs/docs/commit/f2de15385040034ffa044ad2f0a37990d1beedbc の反映です
> Swapped Chrome Extension URL to a non-beta version

- src/guide/essentials/computed.md
resolve #2587 
https://github.com/vuejs/docs/commit/4e0fa3e29102ef5bb6d96d1334452b503985bce0 の反映です
> docs(computed): correct parameter positions in the computed example

- .vitepress/config.ts
- .vitepress/theme/index.ts
- .vitepress/theme/styles/index.css
- .vitepress/theme/styles/vars.css
- package.json
- pnpm-lock.yaml
- src/api/compile-time-flags.md
- src/guide/extras/reactivity-transform.md
- src/guide/extras/web-components.md
- src/guide/quick-start.md
- src/guide/reusability/plugins.md
- src/guide/scaling-up/ssr.md
- src/guide/scaling-up/testing.md
- src/guide/scaling-up/tooling.md
- src/tutorial/src/step-1/description.md
resolve #2593 
https://github.com/vuejs/docs/commit/a3c31debcb81a93806eee63c882ba7ec0c8bc15d の反映です
> feat: enhance code block & code group

- pnpm-lock.yaml
resolve #2597
https://github.com/vuejs/docs/commit/c3a649dbae505b5adf474be9bd4918ab3cff2f5f の反映です
> chore(deps): bump vue from 3.5.16 to 3.5.17

- src/api/sfc-script-setup.md
- src/guide/built-ins/transition.md
- src/guide/components/provide-inject.md
- src/guide/components/v-model.md
- src/guide/essentials/component-basics.md
- src/guide/extras/web-components.md
- src/guide/reusability/composables.md
- src/guide/reusability/plugins.md
- src/guide/scaling-up/ssr.md
- src/guide/scaling-up/state-management.md
- src/guide/scaling-up/testing.md
- src/guide/typescript/composition-api.md
- src/style-guide/rules-recommended.md
- src/tutorial/src/step-12/description.md
resolve #2600
https://github.com/vuejs/docs/commit/9a3038b6a5a0a9b693a1241d0fb4c2368f22903c の反映です
> feat: more enhanced code blocks

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
resolves #2606
Cherry picked from https://github.com/vuejs/docs/commit/ce81e35610eaacb795db37f8eeac9b9d82045cd8
> chore: set up viteconf banner (#2606)

- pnpm-lock.yaml
resolve #2625
https://github.com/vuejs/docs/commit/9e823483159ad0ee1b6fb8663d1f0455c9d9eda9 の反映です
> chore(deps): bump vitepress from 1.6.3 to 1.6.4

- src/guide/reusability/custom-directives.md
- src/guide/typescript/composition-api.md
- src/guide/typescript/options-api.md
resolve #2633
https://github.com/vuejs/docs/commit/595576c1c6fe48cd7cb8ac30fa1075da101bf4d4 の反映です
> docs(directives): using global custom directives with typescript
